import type { PracticeStage } from '../practiceProgress';

export type A1Row =
    | [PracticeStage, string, number, string]
    | [PracticeStage, string, number, string, string[]];

function yn(text: string): string {
    return `${text}\n(1 = igen, 0 = nem)`;
}

export const cauchy: A1Row[] = [
    [1, yn('Az (1/n) sorozat Cauchy-sorozat ℝ-ben?'), 1, 'konvergens ⇒ Cauchy'],
    [1, yn('Az (n) sorozat Cauchy-sorozat?'), 0, 'divergens'],
    [1, yn('Az ((−1)^n) sorozat Cauchy?'), 0, '|a_{n+1}−a_n|=2'],
    [1, yn('Az (1/n²) sorozat Cauchy?'), 1, 'konvergens'],
    [1, yn('Az (n/(n+1)) sorozat Cauchy?'), 1, '→1'],
    [1, yn('Az ((−1)^n / n) sorozat Cauchy?'), 1, '→0'],
    [1, yn('Az (2^n) sorozat Cauchy?'), 0, '→∞'],
    [1, yn('Az ((−1)^n n) sorozat Cauchy?'), 0, 'oszcillál, nő'],
    [1, yn('A konstans 5,5,5,… sorozat Cauchy?'), 1, 'igen'],
    [1, yn('Az (√n) sorozat Cauchy?'), 0, '→∞'],
    [1, yn('Az (1/√n) sorozat Cauchy?'), 1, '→0'],
    [1, yn('Az (sin n) sorozat Cauchy?'), 0, 'nem konvergens'],
    [1, yn('Az (n + 1/n) sorozat Cauchy?'), 0, '→∞'],
    [1, yn('Az ((1+1/n)^n) sorozat Cauchy?'), 1, '→e'],
    [1, yn('A harmonikus H_n Cauchy?'), 0, '→∞'],
    [1, yn('Az (n²) sorozat Cauchy?'), 0, '→∞'],
    [1, yn('Az (1/2^n) sorozat Cauchy?'), 1, '→0'],
    [1, yn('Az (ln n) sorozat Cauchy (n≥1)?'), 0, '→∞'],
    [1, yn('Az (n sin(1/n)) sorozat Cauchy?'), 1, '→1'],
    [1, yn('Az ((−1)^n / n²) sorozat Cauchy?'), 1, '→0'],
    [2, yn('ℝ-ben Cauchy ⇔ konvergens?'), 1, 'teljesség'],
    [2, yn('ℚ-ben minden Cauchy-sorozat konvergens ℚ-ben?'), 0, 'nem teljes'],
    [2, yn('Minden konvergens sorozat Cauchy? (metrikus tér)'), 1, 'igen'],
    [2, yn('Ha (a_n) Cauchy, akkor korlátos?'), 1, 'igen'],
    [2, yn('Ha (a_n) korlátos, akkor Cauchy?'), 0, '(−1)^n'],
    [2, yn('Cauchy-sorozat részsorozata Cauchy?'), 1, 'igen'],
    [2, yn('Ha (a_n) Cauchy és (b_n) Cauchy, (a_n+b_n) Cauchy?'), 1, 'igen'],
    [2, yn('Ha (a_n) Cauchy és (b_n) Cauchy, (a_n b_n) Cauchy?'), 1, 'igen'],
    [2, 'ε=1/10. Az (1/n)-hez melyik N elég: N=11? (1=igen, |a_n−a_m|<1/10 ha n,m≥11)', 1, '1/11<0.1'],
    [2, yn('Ha |a_{n+1}−a_n| ≤ 1/2^n, akkor (a_n) Cauchy?'), 1, 'geometriai majoráns'],
    [2, yn('Ha |a_{n+1}−a_n| → 0, akkor (a_n) Cauchy?'), 0, 'H_n'],
    [2, yn('Két Cauchy-sorozat különbsége Cauchy?'), 1, 'igen'],
    [2, yn('Egy Cauchy-sorozatnak van konvergens részsorozata ℝ-ben?'), 1, 'korlátos + BW'],
    [2, yn('Ha egy Cauchy-sorozatnak van konvergens részsorozata, az egész konvergens?'), 1, 'igen'],
    [2, yn('Az (√2 racionális közelítései) Cauchy ℚ-ben?'), 1, 'Cauchy, de limit ∉ ℚ'],
    [2, yn('Véges metrikus térben minden Cauchy-sorozat konvergens?'), 1, 'teljes (diszkrét)'],
    [2, yn('(a_n) Cauchy ⇒ a_{n+1}−a_n → 0?'), 1, 'szükséges'],
    [2, yn('C[0,1] a max-normával teljes (Cauchy ⇒ egyenletes konvergencia)?'), 1, 'igen'],
    [2, yn('Nyílt (0,1) a szokásos metrikával teljes?'), 0, '1/n Cauchy, limit 0 ∉ (0,1)'],
    [2, yn('[0,1] teljes?'), 1, 'zárt ℝ-ben'],
    [3, yn('Ha ∀ε>0 ∃N: n≥N ⇒ |a_n−L|<ε, akkor (a_n) Cauchy?'), 1, 'konvergens'],
    [3, yn('Cauchy-kritérium sorokra: s_n Cauchy ⇔ a sor konvergens ℝ-ben?'), 1, 'igen'],
    [3, yn('Az (sin n / n) Cauchy?'), 1, '→0'],
    [3, yn('Az (n/(n+1) − 1) = (−1)/(n+1) Cauchy?'), 1, '→0'],
    [3, 'N becslés: |1/n−1/m|<10^{-2} ha n,m ≥ 101? (1=igen)', 1, '1/101<0.01'],
    [3, yn('Ekvivalens Cauchy-sorozatok ugyanoda tartanak ℝ-ben?'), 1, 'igen'],
    [3, yn('Ha (a_n) nem korlátos, lehet Cauchy?'), 0, 'nem'],
    [3, yn('Kompletté tétel: minden metrikus térnek van teljessé tétele?'), 1, 'igen'],
    [3, yn('Az (H_{n+1}−H_n)=1/(n+1) Cauchy? (ez a differencia, nem H_n)'), 1, '→0, maga a tag Cauchy mint sorozat'],
    [3, yn('A geometriai 1/2^n részletösszegei Cauchy-k?'), 1, 'konvergens sor'],
    [3, yn('A harmonikus sor részletösszegei Cauchy-k?'), 0, 'divergens'],
    [3, yn('Ha a_n = ∑_{k=1}^n 1/k², (a_n) Cauchy?'), 1, 'p=2'],
    [3, yn('Banach-tér = teljes normált tér?'), 1, 'igen'],
    [3, yn('Hilbert-tér = teljes skalárszorzatos tér?'), 1, 'igen'],
    [3, yn('Ha |a_n − a_m| ≤ |n−m|/nm, akkor Cauchy?'), 1, '|1/n−1/m|'],
    [3, yn('Gyors Cauchy: ∑ |a_{n+1}−a_n| < ∞ ⇒ Cauchy?'), 1, 'abszolút konvergens teleszkóp'],
    [3, yn('ℓ² Cauchy-sorozata konvergens ℓ²-ben?'), 1, 'Hilbert'],
    [3, yn('c_00 (véges tartójú sorozatok) ℓ^∞-ban teljes?'), 0, 'sűrű c_0-ban'],
    [3, yn('Ha (a_n) Cauchy ℚ-ben, van-e valós határértéke?'), 1, 'ℝ teljes'],
    [3, yn('Két ekvivalens Cauchy-sorozat különbsége → 0?'), 1, 'definíció'],
    [4, yn('Cantor-metszet: átmérő → 0 + zárt nemüres ⇒ egy pont (teljes tér)?'), 1, 'igen'],
    [4, yn('Baire: teljes metrikus tér 1. kategóriájú?'), 0, 'Baire: 2. kategória'],
    [4, yn('Egyenletes Cauchy folytonos függvényekre ⇒ egyenletes konvergencia C[a,b]-n?'), 1, 'teljes'],
    [4, yn('Pontonként Cauchy folytonos függvényekre ⇒ a limit folytonos?'), 0, 'nem egyenletes'],
    [4, yn('Ha ∀k ∃N: n,m≥N ⇒ |a_n−a_m|<1/k, ez Cauchy?'), 1, 'ε=1/k'],
    [4, yn('(√2 tizedesapproximációi) Cauchy?'), 1, 'igen'],
    [4, yn('Nem teljes térben létezhet Cauchy divergens sorozat?'), 1, 'igen'],
    [4, yn('Kompakt metrikus tér teljes?'), 1, 'igen'],
    [4, yn('Teljes tér korlátos zárt részhalmaza mindig kompakt?'), 0, 'ℝ^∞, zárt gömb'],
    [4, yn('ℝ^n euklideszi metrikával teljes?'), 1, 'igen'],
    [4, yn('Ha d és ρ ekvivalens metrikák, Cauchy-ság megmarad?'), 1, 'igen (lipschitz/ekv.)'],
    [4, yn('Diszkrét metrikában Cauchy-sorozat végül konstans?'), 1, 'ε<1'],
    [4, yn('p-adikus ℚ_p teljes?'), 1, 'igen'],
    [4, yn('Cauchy-szorzat: ha a_n→A, b_n→B Cauchy, a_n b_n → AB?'), 1, 'igen'],
    [4, 'ε=10^{-3}. (1/2^n) Cauchy: elég-e N=10? |a_n|<1/1024<0.001 (1=igen)', 1, 'igen'],
    [4, yn('Ha (s_n) a ∑ a_k részletösszege és Cauchy, a_n→0?'), 1, 'szükséges'],
    [4, yn('a_n→0 elégséges Cauchy-részletösszeghez?'), 0, 'harmonikus'],
    [4, yn('Abszolút konvergens sor részletösszegei Cauchy-k?'), 1, 'igen'],
    [4, yn('Feltételesen konvergens sor részletösszegei Cauchy-k ℝ-ben?'), 1, 'konvergens'],
    [4, yn('Riemann-átrendezés megváltoztathatja a Cauchy-jelleget (az összeget)?'), 1, 'az összeg más lehet'],
    [5, yn('Lipschitz-függvény Cauchy-sorozatot Cauchy-ba visz?'), 1, 'igen'],
    [5, yn('Egyenletesen folytonos f Cauchy-t Cauchy-ba visz?'), 1, 'igen'],
    [5, yn('Csak folytonos f mindig Cauchy-t Cauchy-ba visz?'), 0, 'f(x)=x² ℝ-n, a_n=n'],
    [5, yn('Kontrakció teljes téren Banach-fixpontot ad?'), 1, 'igen'],
    [5, yn('Az Picard-iteráció Cauchy, ha a leképezés kontrakció?'), 1, 'igen'],
    [5, yn('Ha ∑ ||x_{n+1}−x_n|| < ∞ Banach-térben, (x_n) konvergens?'), 1, 'abszolút Cauchy'],
    [5, yn('Gyenge Cauchy Hilbert-térben gyengén konvergens (reflexív)?'), 1, 'igen Hilbertben'],
    [5, yn('Norma-Cauchy ⇒ gyenge Cauchy?'), 1, 'igen'],
    [5, yn('Gyenge Cauchy ⇒ norma-Cauchy?'), 0, 'nem'],
    [5, yn('L²[0,1] teljes?'), 1, 'igen'],
    [5, yn('C[0,1] L²-normával teljes?'), 0, 'nem, lezárt L²'],
    [5, yn('Racionális Cauchy-sorozat reprezentálja a valós számot?'), 1, 'konstrukció'],
    [5, yn('Két racionális Cauchy-sorozat ekvivalens, ha különbségük → 0?'), 1, 'igen'],
    [5, yn('A (1+1/n)^n racionális tagú Cauchy?'), 1, 'konvergens ℝ-ben'],
    [5, yn('Az (sin(n²)/n) sorozat Cauchy ℝ-ben?'), 1, '→ 0, konvergens'],
    [5, yn('Minden Cauchy-sorozat korlátos ingadozású?'), 0, 'nem, pl. alkalmas oszcilláló konvergens'],
    [5, yn('Teljes tér zárt altere teljes?'), 1, 'igen'],
    [5, yn('Teljes tér sűrű valódi altere teljes?'), 0, 'ℚ ⊂ ℝ'],
    [5, yn('Véges dimenziós normált tér teljes?'), 1, 'igen'],
    [5, yn('Minden Cauchy-háló (net) konvergens ℝ-ben?'), 1, 'teljesség'],
    [6, yn('Ascoli: egyenletesen korlátos, egyenlőn folytonos C[a,b]-ben relatív kompakt?'), 1, 'igen'],
    [6, yn('Relatív kompakt ⇒ minden sorozatnak van Cauchy-részsorozata?'), 1, 'igen'],
    [6, yn('A π tizedesjegyeinek sorozata Cauchy? (a közelítő törtek)'), 1, 'igen'],
    [6, yn('Ha d(x_n, x_m) ≤ ∑_{k=min}^{max} ε_k és ∑ε_k<∞, Cauchy?'), 1, 'igen'],
    [6, yn('Ultrametrikus térben a legerősebb tag dönti el a Cauchy-t?'), 1, 'igen'],
    [6, yn('p-adikus |∑_{k=n}^m a_k|_p ≤ max |a_k|_p Cauchy-kritérium?'), 1, 'igen'],
    [6, yn('Sobolev W^{1,2} teljes?'), 1, 'igen'],
    [6, yn('Schwartz-tér teljes metrizálható?'), 1, 'Fréchet'],
    [6, yn('Ha f_n egyenletesen Cauchy és minden f_n mérhető, a limit mérhető?'), 1, 'igen'],
    [6, yn('Majdnem mindenütt Cauchy L^p-ben (1≤p<∞) részsorozattal m.m. konvergens?'), 1, 'igen'],
    [6, yn('Gyenge kompaktság Hilbert-gömb: minden korlátosnak van gyenge Cauchy-részsorozata?'), 1, 'igen'],
    [6, yn('Nem teljes tér faktora lehet teljes (kompletté tétel)?'), 1, 'igen'],
    [6, yn('Cauchy-szűrő konvergens ⇔ a tér teljes?'), 1, 'igen'],
    [6, yn('Egyenletes struktúrában Cauchy általánosítja a metrikus Cauchy-t?'), 1, 'igen'],
    [6, yn('Ha X teljes, Y zárt X-ben, Y teljes?'), 1, 'igen'],
    [6, yn('Nyílt gömb mindig teljes?'), 0, 'általában nem'],
    [6, yn('Kompletté tétel izometria erejéig egyértelmű?'), 1, 'igen'],
    [6, yn('ℝ Cauchy-sorozatai faktor ℚ Cauchy / ~ ?'), 1, 'konstrukció'],
    [6, yn('Ha |a_n−L|≤1/n, (a_n) Cauchy?'), 1, 'konvergens'],
    [6, yn('Newton-iteráció gyökhöz (egyszeres gyök, f\'≠0) lokálisan Cauchy?'), 1, 'kvadratikus konvergencia'],
];

export const numerikusSorok: A1Row[] = [
    [1, '∑_{n=0}^∞ (1/2)^n = ?', 2, '1/(1−1/2)=2'],
    [1, '∑_{n=1}^∞ (1/2)^n = ?', 1, '1'],
    [1, '∑_{n=0}^∞ (1/3)^n = ?', 1.5, '1/(1−1/3)=3/2'],
    [1, '∑_{n=1}^∞ 1/(n(n+1)) = ?', 1, 'teleszkóp'],
    [1, yn('∑ 1/n konvergens?'), 0, 'harmonikus'],
    [1, yn('∑ 1/n² konvergens?'), 1, 'p=2>1'],
    [1, yn('∑ 1/n³ konvergens?'), 1, 'p=3'],
    [1, yn('∑ 1/√n konvergens?'), 0, 'p=1/2≤1'],
    [1, 'Geometriai: első tag 3, hányados 1/2, végtelen összeg?', 6, '3/(1−1/2)=6'],
    [1, yn('Ha a_n ↛ 0, a ∑ a_n konvergens?'), 0, 'szükséges feltétel'],
    [1, yn('Ha a_n → 0, a ∑ a_n konvergens?'), 0, 'nem elégséges'],
    [1, '∑_{n=0}^∞ 0,1 · (0,1)^n ? 0.1/0.9≈0.111', 0.111, '0,1/(1−0,1)'],
    [1, '∑_{n=1}^3 (1/2)^n = ?', 0.875, '0.5+0.25+0.125'],
    [1, yn('Véges sok tag megváltoztatása a konvergenciát megváltoztatja?'), 0, 'nem'],
    [1, yn('∑ q^n konvergens, ha |q|<1?'), 1, 'igen'],
    [1, yn('∑ q^n konvergens, ha |q|>1?'), 0, 'nem, a_n↛0'],
    [1, '∑_{n=1}^∞ 3/10^n = ?', 0.333, '0,333…=1/3'],
    [1, yn('Pozitív tagú sor vagy konvergens, vagy +∞-hez divergál?'), 1, 'igen'],
    [1, 's_n = 1 − 1/n. Mennyi lim s_n?', 1, '1'],
    [1, '∑_{n=1}^∞ 2/3^n = ?', 1, '2·(1/3)/(1−1/3)=1'],
    [2, '∑_{n=1}^∞ 1/(n(n+2)) = ? (1/2 teleszkóp)', 0.75, '1/2 · (1+1/2)=3/4'],
    [2, yn('∑ (−1)^{n+1}/n konvergens?'), 1, 'Leibniz / ln2'],
    [2, '∑_{n=0}^∞ x^n |x|=1/2 összege?', 2, '2'],
    [2, yn('∑ n / 2^n konvergens?'), 1, 'igen, összeg 2'],
    [2, '∑_{n=1}^∞ n / 2^n = ?', 2, '2'],
    [2, yn('∑ n² / 2^n konvergens?'), 1, 'igen'],
    [2, yn('p-sor: ∑ 1/n^p konvergens ⇔ p>1?'), 1, 'igen'],
    [2, yn('∑ 1/(n ln n) (n≥2) konvergens?'), 0, 'integrálkritérium'],
    [2, yn('∑ 1/(n (ln n)²) (n≥2) konvergens?'), 1, 'integrál'],
    [2, 'Geometriai |q|=0.8, a=1, összeg?', 5, '1/0.2=5'],
    [2, yn('Ha 0≤a_n≤b_n és ∑ b_n konv., ∑ a_n konv.?'), 1, 'összehasonlító'],
    [2, yn('Ha 0≤a_n≤b_n és ∑ a_n div., ∑ b_n div.?'), 1, 'igen'],
    [2, '∑_{n=0}^∞ (−1/2)^n = ?', 0.667, '1/(1+1/2)=2/3'],
    [2, yn('∑ (n+1)/n^3 konvergens?'), 1, '~ 1/n²'],
    [2, yn('∑ 1/(n+1) konvergens?'), 0, 'harmonikus'],
    [2, 'Teleszkóp ∑ (1/n − 1/(n+1)) = ?', 1, '1'],
    [2, yn('Konvergens sor általános tagja → 0?'), 1, 'szükséges'],
    [2, yn('∑ 2^n / n! konvergens?'), 1, 'e² − 1 jelleg, igen'],
    [2, yn('∑ n! / n^n konvergens?'), 1, 'igen'],
    [2, '∑_{n=1}^∞ 1/3^n = ?', 0.5, '1/2'],
    [3, '∑ n x^{n} |x|=1/2? összeg x/(1−x)² = 2', 2, '2'],
    [3, yn('Cauchy-szorzat két abszolút konvergens sornak abszolút konvergens?'), 1, 'igen'],
    [3, yn('Mertens: abszolút × konvergens ⇒ Cauchy-szorzat konvergens?'), 1, 'igen'],
    [3, '∑_{n=1}^∞ 1/(n²+n) = ∑ (1/n−1/(n+1)) = ?', 1, '1'],
    [3, yn('∑ sin n / n² konvergens?'), 1, 'abszolút, |sin|≤1'],
    [3, yn('∑ sin n / n konvergens?'), 1, 'Dirichlet'],
    [3, yn('∑ sin n konvergens?'), 0, 'a_n ↛ 0'],
    [3, 'ζ(2)=∑ 1/n² ≈ ? Három tizedes.', 1.645, 'π²/6'],
    [3, yn('∑ (−1)^n / √n konvergens?'), 1, 'Leibniz'],
    [3, yn('∑ (−1)^n / √n abszolút konvergens?'), 0, 'p=1/2'],
    [3, yn('Riemann-átrendezés: feltételesen konvergens sor bármely összegre átrendezhető?'), 1, 'igen'],
    [3, yn('Abszolút konvergens sor átrendezése ugyanazt adja?'), 1, 'igen'],
    [3, 'Geometriai |q|=1/4, a=4, összeg?', 5.333, '4/(3/4)=16/3≈5,333'],
    [3, yn('∑ ln(1+1/n) konvergens?'), 0, '~ 1/n'],
    [3, yn('∑ (√(n+1)−√n) konvergens?'), 0, 'teleszkóp → ∞'],
    [3, yn('∑ (√(n+1)−√n)/n konvergens?'), 1, '~ 1/(2 n^{3/2})'],
    [3, '∑_{n=0}^∞ 1/n! = ? Három tizedes (e).', 2.718, 'e'],
    [3, '∑_{n=0}^∞ 1/(2^n n!) ? √e ≈ 1.649', 1.649, 'e^{1/2}'],
    [3, yn('Ha s_n korlátos és a_n>0, ∑ a_n konvergens?'), 1, 'monoton korlátos'],
    [3, yn('∑ 1/(n ln² n) n≥2 konvergens?'), 1, 'integrál'],
    [4, yn('Gyökkritérium: lim sup |a_n|^{1/n} < 1 ⇒ konvergens?'), 1, 'igen'],
    [4, yn('Aránykritérium: lim |a_{n+1}/a_n| < 1 ⇒ konvergens?'), 1, 'igen'],
    [4, yn('Ha az arány → 1, a teszt dönt?'), 0, 'határeset'],
    [4, yn('Integrálkritérium: f csökkenő pozitív, ∑f(n) és ∫f ugyanaz a konvergencia?'), 1, 'igen'],
    [4, yn('Raabe, Gauss-tesztek finomítják az arány 1 esetét?'), 1, 'igen'],
    [4, '∑_{n=1}^∞ n / 3^n = ?  3/4 = 0.75? formula x/(1−x)² x=1/3: (1/3)/(4/9)=3/4', 0.75, '3/4'],
    [4, yn('A centralis binomiális / 16^n sor konvergens?'), 1, 'gyök 4/16 < 1'],
    [4, yn('∑ n^k q^n konvergens minden k-ra, ha |q|<1?'), 1, 'igen'],
    [4, yn('∑ 1/(n log n log log n) divergens elég nagy n-től?'), 1, 'integrál'],
    [4, 'Teleszkóp ∑ (1/√n − 1/√(n+1)) = ?', 1, '1'],
    [4, yn('Kondenzációs Cauchy: a_n↓0, ∑ a_n ⇔ ∑ 2^k a_{2^k}?'), 1, 'igen'],
    [4, yn('∑ 1/n^p (log n)^q viselkedését az integrál dönti el?'), 1, 'igen'],
    [4, yn('Abel-szummáció: ha ∑ a_n konv., (1−r)∑ s_n r^n → összeg r→1−?'), 1, 'Abel'],
    [4, yn('A Cesaro-szummacio gyengebb, mint a klasszikus konvergencia?'), 0, 'erossebb, tobbet szummal'],
    [4, yn('Grandí 1−1+1−1 Cesàro összege 1/2?'), 1, 'igen'],
    [4, yn('∑ (−1)^n n divergens (nem Leibniz, mert n↛0? n→∞)?'), 1, 'a_n ↛ 0, divergens'],
    [4, '∑_{n=1}^∞ 1/(n(n+1)(n+2)) = 1/4', 0.25, '1/4'],
    [4, yn('Weierstrass M-teszt: |u_n(x)|≤M_n, ∑M_n konv. ⇒ egyenletes absz. konv.?'), 1, 'igen'],
    [4, yn('Egyenletes konvergencia megőrzi a folytonosságot?'), 1, 'igen'],
    [4, yn('∑ x^n / n  |x|<1 konvergens?'), 1, '−ln(1−x)'],
    [5, '∑_{n=1}^∞ x^n / n  x=1/2 ? −ln(1/2)=ln2≈0.693', 0.693, 'ln 2'],
    [5, yn('∑ x^n / n²  |x|≤1 konvergens?'), 1, 'igen, x=−1 is'],
    [5, yn('∑ n x^{n−1} |x|<1 = 1/(1−x)²?'), 1, 'igen'],
    [5, yn('Hatványsor konvergenciasugara Cauchy–Hadamard: 1/R = lim sup |c_n|^{1/n}?'), 1, 'igen'],
    [5, yn('A konvergenciakör belsejében abszolút konvergens a hatványsor?'), 1, 'igen'],
    [5, yn('A konvergenciakörön a viselkedés vegyes lehet?'), 1, 'igen'],
    [5, 'R: ∑ n! x^n sugara?', 0, 'R=0'],
    [5, 'R: ∑ x^n / n! sugara? Add meg 1-et ha R=∞, 0-t ha R=0. Itt R=∞ → 1', 1, 'R=∞'],
    [5, yn('Taylor-sor mindig előállítja a függvényt a körön?'), 0, 'pl. e^{−1/x²}'],
    [5, yn('∑ a_n konv. ⇒ ∑ a_n / n konv.?'), 0, 'nem mindig, de Dirichlet gyakran'],
    [5, yn('Abel: ha ∑ a_n konv., a hatványsor x→1− a összeghez tart?'), 1, 'Abel-tétel'],
    [5, yn('∑_{n=1}^∞ (−1)^{n+1}/n = ln 2?'), 1, 'igen'],
    [5, '∑_{n=1}^∞ (−1)^{n+1}/n = ? Három tizedes.', 0.693, 'ln 2'],
    [5, yn('Pringsheim: pozitív csökkenő a_n, ∑a_n konv. ⇒ n a_n → 0?'), 1, 'igen'],
    [5, yn('n a_n → 0 elégséges pozitív csökkenő sornál?'), 0, '1/(n ln n)'],
    [5, yn('Összehasonlítás limesze: a_n/b_n → L∈(0,∞) ⇒ ugyanaz a konv.?'), 1, 'igen'],
    [5, yn('∑ (sin n)/n^p konvergens minden p>0-ra?'), 1, 'Dirichlet p>0'],
    [5, yn('∑ (sin n)/n^p abszolút konvergens ⇔ p>1?'), 1, 'igen'],
    [5, yn('Fourier-sor pontonként konvergálhat, de nem abszolút?'), 1, 'igen'],
    [5, yn('Parseval: l2 egyutthatok osszege egyenlo ||f||^2?'), 1, 'igen'],
    [6, yn('Riemann-zeta ∑ n^{−s} konvergens Re s>1?'), 1, 'igen'],
    [6, yn('Dirichlet-eta η(s)=(1−2^{1−s})ζ(s) konvergens Re s>0?'), 1, 'igen'],
    [6, yn('Euler-szorzat ζ(s)=∏ (1−p^{−s})^{-1} Re s>1?'), 1, 'igen'],
    [6, yn('∑ μ(n)/n = 0? (1= a tétel igaz, prímszámétel ekv.)'), 1, 'igen'],
    [6, yn('Lacunary sor ∑ z^{2^n} a körön sűrűn szinguláris?'), 1, 'igen'],
    [6, yn('Weierstrass ∑ b^n cos(a^n π x) sehol nem deriválható alkalmas a,b-re?'), 1, 'igen'],
    [6, yn('∑ 1/(n (ln n)^p ) n≥2 konvergens ⇔ p>1?'), 1, 'igen'],
    [6, yn('Bertrand-sorok: a log-skála integrálkritériuma?'), 1, 'igen'],
    [6, yn('Hölder, Cesàro (C,α) szummáció hierarchia?'), 1, 'igen'],
    [6, yn('Tauber: ha a_n=o(1/n) és Abel-szummálható, akkor konvergens?'), 1, 'igen'],
    [6, yn('Hardy–Littlewood Tauber a_n=O(1/n)?'), 1, 'igen'],
    [6, yn('∑ a_n b_n abszolút, ha (a_n)∈ℓ², (b_n)∈ℓ²?'), 1, 'Cauchy–Schwarz'],
    [6, yn('∑ |a_n|² <∞ nem implikál ∑ |a_n|<∞?'), 1, '1/n'],
    [6, yn('Ortonormált rendszer Fourier-együtthatói ℓ² (Bessel)?'), 1, 'igen'],
    [6, yn('Riesz–Fischer: ℓ² együtthatókhoz van L² függvény?'), 1, 'igen'],
    [6, yn('Kondenzáció 1/(n ln n): 2^k * 1/(2^k * k) = 1/k divergens?'), 1, 'igen'],
    [6, yn('A ∑ (−1)^n / ln n (n≥2) konvergens?'), 1, 'Leibniz'],
    [6, yn('A ∑ (−1)^n / ln n abszolút?'), 0, 'harmonikus log'],
    [6, yn('Többszörös sorok Fubini: abszolút ⇒ a sorrend mindegy?'), 1, 'igen'],
    [6, yn('Nem abszolút kettős sor sorrendje számít?'), 1, 'igen'],
];
