import type { PracticeStage } from '../practiceProgress';
import type { Question } from './types';
import { cauchy, numerikusSorok } from './analizis1LevelsB';
import {
    abszFelt,
    folytonosTetelek,
    folytonossag,
    fvHatar,
    konvKrit,
    nevezetes,
} from './analizis1LevelsC';
import { komplex } from './analizis1LevelsKomplex';

/** Analízis I. egyetemi témakör-azonosítók — `a1-` prefix, hogy ne ütközzenek érettségi includes()-szel. */
export const ANALIZIS1_TOPIC_IDS = [
    'a1-valos-szamok',
    'a1-komplex',
    'a1-szamsorozatok',
    'a1-seq-hatarertek',
    'a1-cauchy',
    'a1-numerikus-sorok',
    'a1-konv-kriteriumok',
    'a1-absz-felteteles',
    'a1-fv-hatarertek',
    'a1-nevezetes-lim',
    'a1-folytonossag',
    'a1-folytonos-tetelek',
] as const;

export type Analizis1TopicId = (typeof ANALIZIS1_TOPIC_IDS)[number];

const T = 'multiplication' as const;

function card(
    stage: PracticeStage,
    question: string,
    answer: number,
    expression: string,
    expectedSet?: string[]
): Question {
    return expectedSet
        ? { stage, question, answer, type: T, expression, expectedSet }
        : { stage, question, answer, type: T, expression };
}

type Row = [PracticeStage, string, number, string] | [PracticeStage, string, number, string, string[]];

function bank(rows: Row[]): Question[] {
    return rows.map((r) => card(r[0], r[1], r[2], r[3], r[4]));
}

function yn(text: string): string {
    return `${text}\n(1 = igen, 0 = nem)`;
}

const valos: Row[] = [
    // 1. szint — véges halmaz, intervallum
    [1, 'Mennyi max{2, 5, 1, 8}?', 8, '8'],
    [1, 'Mennyi min{−3, 0, 4, −1}?', -3, '−3'],
    [1, 'Mennyi inf[0, 1]?', 0, '0'],
    [1, 'Mennyi sup[0, 1]?', 1, '1'],
    [1, 'Mennyi inf(0, 1)?', 0, '0'],
    [1, 'Mennyi sup(0, 1)?', 1, '1'],
    [1, 'Mekkora a [−2, 3] intervallum hossza?', 5, '3−(−2)=5'],
    [1, yn('Igaz-e, hogy 0 ∈ (0, 1)?'), 0, '0 nincs nyílt (0,1)-ben'],
    [1, yn('Igaz-e, hogy 1 ∈ [0, 1]?'), 1, '1 a zárt intervallum vége'],
    [1, 'Mennyi max{−7, −2, −9}?', -2, '−2'],
    [1, 'Mennyi inf{1/n : n = 1, 2, 3, …}?', 0, '0 a legnagyobb alsó korlát'],
    [1, 'Mennyi sup{1/n : n = 1, 2, 3, …}?', 1, '1 = 1/1'],
    [1, yn('√2 racionális szám?'), 0, '√2 irracionális'],
    [1, yn('π racionális szám?'), 0, 'π irracionális'],
    [1, yn('Minden természetes szám valós szám?'), 1, 'ℕ ⊂ ℝ'],
    [1, 'Mennyi |−4|?', 4, '4'],
    [1, 'Mennyi dist(−3, 5)?', 8, '|5−(−3)|=8'],
    [1, 'Mennyi ⌊2,7⌋ (alsó egészrész)?', 2, '2'],
    [1, 'Mennyi ⌈2,1⌉ (felső egészrész)?', 3, '3'],
    [1, yn('A {1, 2, 3} halmaz korlátos ℝ-ben?'), 1, 'igen, véges'],
    // 2. szint — inf/sup, korlátosság
    [2, 'Mennyi inf{n + 1/n : n ≥ 1}?', 2, 'n=1-nél 2, utána nagyobb'],
    [2, 'Mennyi sup(0, 2]?', 2, '2'],
    [2, 'Mennyi inf[−1, 4)?', -1, '−1'],
    [2, 'Mennyi sup{x ∈ ℚ : x < √2}? Három tizedesjegy (√2).', 1.414, '√2 ≈ 1,414'],
    [2, yn('A ℕ halmaz felülről korlátos ℝ-ben?'), 0, 'Arkhimédész: nincs felső korlát'],
    [2, yn('A (0, 1) halmaz alulról korlátos?'), 1, 'pl. 0 alsó korlát'],
    [2, 'Mennyi inf{2 − 1/n : n ≥ 1}?', 1, 'n=1-nél 1'],
    [2, 'Mennyi sup{2 − 1/n : n ≥ 1}?', 2, '2-höz tart, 2-t nem éri el'],
    [2, yn('Létezik-e max(0, 1)?'), 0, 'nyílt, nincs maximum'],
    [2, yn('Létezik-e min[0, 1]?'), 1, 'min = 0'],
    [2, yn('Az (−∞, 3] halmaz alulról korlátos ℝ-ben?'), 0, 'nincs véges alsó korlát'],
    [2, yn('Az (0, 1) ∪ (1, 2) halmaz összefüggő ℝ-ben?'), 0, '1 hiányzik'],
    [2, 'Mennyi sup{−n : n ∈ ℕ}? (ℕ = {1, 2, …})', -1, '−1'],
    [2, yn('A {−n : n ∈ ℕ} halmaz alulról korlátos?'), 0, '−n → −∞'],
    [2, yn('{1/n} alulról korlátos?'), 1, '0 alsó korlát'],
    [2, 'Mennyi max{1, 1/2, 1/3, 1/4}?', 1, '1'],
    [2, 'Mennyi min{1, 1/2, 1/3, 1/4}?', 0.25, '1/4'],
    [2, yn('Minden nemüres, felülről korlátos ℝ-beli halmaznak van szuprémuma ℝ-ben?'), 1, 'teljesség'],
    [2, yn('Minden nemüres, felülről korlátos ℚ-beli halmaznak van szuprémuma ℚ-ben?'), 0, 'ℚ nem teljes'],
    [2, 'Mennyi inf{x ∈ ℝ : x² > 2}? Három tizedesjegy (−√2).', -1.414, '−√2'],
    // 3. szint — rendezettség, Archimédesz
    [3, yn('Létezik n ∈ ℕ, hogy n > 1000?'), 1, 'Arkhimédészi tulajdonság'],
    [3, yn('Létezik n ∈ ℕ, hogy 1/n < 0,001?'), 1, '1/n → 0'],
    [3, yn('Két valós szám között mindig van racionális?'), 1, 'ℚ sűrű ℝ-ben'],
    [3, yn('Két valós szám között mindig van irracionális?'), 1, 'ℝ\\ℚ sűrű'],
    [3, 'Hány racionális van (0, 1)-ben? Add meg 0-t, ha véges, 1-et ha végtelen.', 1, 'végtelen sok'],
    [3, yn('Ha a ≤ b és b ≤ a, akkor a = b?'), 1, 'antiszimmetria'],
    [3, yn('Ha a < b és b < c, akkor a < c?'), 1, 'tranzitivitás'],
    [3, 'Mennyi inf{q ∈ ℚ : q > π}? Három tizedesjegy (π).', 3.142, 'π ≈ 3,142'],
    [3, 'Mennyi sup{q ∈ ℚ : q < π}? Három tizedesjegy (π).', 3.142, 'π'],
    [3, yn('0 a {1/n} halmaz minimuma?'), 0, '0 nincs a halmazban'],
    [3, yn('1 a {1/n} halmaz maximuma?'), 1, '1 = 1/1'],
    [3, 'Mennyi inf[3, 3]?', 3, 'egy pont'],
    [3, 'Mennyi sup{ n/(n+1) : n ≥ 1 }?', 1, 'tart 1-hez'],
    [3, yn('Van-e legkisebb pozitív valós szám?'), 0, 'nincs'],
    [3, yn('Van-e legnagyobb negatív valós szám?'), 0, 'nincs'],
    [3, 'Mennyi |a| definíció szerint, ha a = −5?', 5, '5'],
    [3, yn('|x+y| ≤ |x|+|y| mindig igaz?'), 1, 'háromszög-egyenlőtlenség'],
    [3, yn('|x| = 0 ⇔ x = 0?'), 1, 'norma'],
    [3, 'Mennyi inf{ x ∈ ℝ : x³ > 8 }?', 2, '2'],
    [3, 'Mennyi sup{ x ∈ ℝ : x² < 9 }?', 3, '3'],
    // 4. szint — teljesség, Cantor
    [4, yn('Egymásba skatulyázott zárt intervallumok metszete ℝ-ben mindig nemüres?'), 1, 'Cantor'],
    [4, yn('Egymásba skatulyázott nyílt intervallumok metszete mindig nemüres?'), 0, 'pl. (0, 1/n)'],
    [4, yn('Minden Cauchy-sorozat konvergens ℝ-ben?'), 1, 'ℝ teljes'],
    [4, yn('Minden Cauchy-sorozat konvergens ℚ-ben?'), 0, 'ℚ nem teljes'],
    [4, 'Mennyi inf{ √n − ⌊√n⌋ : n ∈ ℕ }?', 0, '0-hoz tetszőlegesen közel'],
    [4, yn('A Bolzano–Weierstrass tétel: minden korlátos sorozatnak van konvergens részsorozata ℝ-ben?'), 1, 'igen'],
    [4, yn('Minden monoton korlátos sorozat konvergens ℝ-ben?'), 1, 'igen'],
    [4, 'Mennyi sup{ x ∈ ℝ : sin x = 0, x ∈ [0, 2π] }? Fokban: 360, radiánban 2π≈6.283. Add meg 2π három tizedesjeggyel.', 6.283, '2π'],
    [4, yn('Ha A ⊂ B, akkor inf A ≥ inf B (feltéve mindkettő nemüres, alulról korlátos)?'), 1, 'igen'],
    [4, yn('Ha A ⊂ B, akkor sup A ≤ sup B (felülről korlátos)?'), 1, 'igen'],
    [4, 'Mennyi inf(ℕ)? (ℕ = {1, 2, …})', 1, '1'],
    [4, yn('ℝ-ben minden nyílt halmaz megszámlálható uniója nyílt?'), 1, 'topológia'],
    [4, yn('ℝ-ben véges sok zárt halmaz uniója zárt?'), 1, 'igen'],
    [4, yn('Végtelen sok zárt halmaz uniója mindig zárt?'), 0, 'ℚ = ∪{q}'],
    [4, 'Mennyi dist(√2, ℚ)?', 0, 'ℚ sűrű'],
    [4, yn('Létezik-e ℝ-ben szigorúan a és b között fekvő c, ha a < b?'), 1, 'rendezettség'],
    [4, 'Mennyi max{ x ∈ [0, 1] : x racionális }?', 1, '1 ∈ ℚ'],
    [4, yn('A [0, 1] ∩ ℚ kompakt ℝ-ben?'), 0, 'nem zárt ℝ-ben / nem teljes'],
    [4, yn('[0, 1] kompakt ℝ-ben?'), 1, 'Heine–Borel'],
    [4, 'Mennyi inf{ e⁻ⁿ : n ≥ 0 }?', 0, '0'],
    // 5. szint
    [5, yn('Ha inf A = sup A, akkor A egyelemű (A nemüres, korlátos)?'), 1, 'igen'],
    [5, 'Mennyi sup{ 1 − 1/n² : n ≥ 1 }?', 1, '1'],
    [5, 'Mennyi inf{ (n+1)/n : n ≥ 1 }?', 1, '1 + 1/n → 1'],
    [5, yn('Minden ℚ-beli Cauchy-sorozat konvergens ℚ-ben?'), 0, 'nem teljes'],
    [5, 'Mennyi inf{ x > 0 : x² ≥ 2 }? Három tizedesjegy.', 1.414, '√2'],
    [5, yn('Az üres halmaznak van szuprémuma ℝ-ben a szokásos definíció szerint (nemüres kell)?'), 0, 'nemüres feltétel'],
    [5, 'Mennyi sup{ n/(2n+1) : n ≥ 1 }?', 0.5, '1/2'],
    [5, yn('|x−y| < ε minden ε>0 esetén ⇒ x=y?'), 1, 'igen'],
    [5, yn('Ha x ≤ y + ε minden ε>0-ra, akkor x ≤ y?'), 1, 'igen'],
    [5, 'Mennyi inf{ 2ⁿ : n ∈ ℤ }?', 0, 'n→−∞'],
    [5, yn('A Dedekind-szelet egyértelműen meghatároz egy valós számot?'), 1, 'konstrukció'],
    [5, 'Mennyi max{ x ∈ ℝ : x² + 2x − 3 ≤ 0 }?', 1, '(x+3)(x−1)≤0 → [−3,1]'],
    [5, 'Mennyi min{ x ∈ ℝ : x² + 2x − 3 ≤ 0 }?', -3, '−3'],
    [5, yn('Minden felülről korlátos monoton növő sorozat konvergens?'), 1, 'igen'],
    [5, yn('Van-e bijekció ℕ és ℚ között?'), 1, 'ℚ megszámlálható'],
    [5, yn('Van-e bijekció ℕ és ℝ között?'), 0, 'ℝ nem megszámlálható'],
    [5, 'Mennyi inf{ |x−√2| : x ∈ ℚ, x≠√2 }?', 0, 'sűrű'],
    [5, yn('Ha A és B nemüres, korlátos, akkor inf(A+B)=inf A + inf B?'), 1, 'igen'],
    [5, yn('sup(−A) = −inf A?'), 1, 'igen'],
    [5, 'Mennyi sup{ sin n : n ∈ ℕ }? (kb. 1, a sorozat sűrű [−1,1]-ben) Add meg 1-et.', 1, '1'],
    // 6. szint
    [6, yn('ℝ minden korlátos zárt intervalluma kompakt?'), 1, 'Heine–Borel'],
    [6, yn('ℝ-ben a kompakt ⇔ zárt és korlátos?'), 1, 'igen'],
    [6, 'Mennyi inf{ x ∈ ℝ : eˣ > 3 }? Három tizedesjegy (ln 3).', 1.099, 'ln 3 ≈ 1,099'],
    [6, yn('Minden nyílt fedésnek van véges részfedése [0,1]-en?'), 1, 'kompaktság'],
    [6, yn('A (0, 1] halmaz kompakt?'), 0, 'nem zárt / 0 hiányzik'],
    [6, 'Mennyi sup{ x ∈ [0, π/2] : sin x < 1/2 }? Fokban 30, radiánban π/6≈0.524. Add meg π/6 három tizedesjeggyel.', 0.524, 'π/6'],
    [6, yn('Ha (I_n) zárt, I_{n+1}⊂I_n és |I_n|→0, a metszet egy pont?'), 1, 'Cantor'],
    [6, yn('Létezik-e ℝ-ben legnagyobb szám?'), 0, 'nincs'],
    [6, 'Mennyi inf{ n^{1/n} : n ≥ 1 }?', 1, 'tart 1-hez, n=1-nél 1, min=1'],
    [6, yn('Minden jólrendezett nemüres ℕ-részhalmaznak van legkisebb eleme?'), 1, 'igen'],
    [6, yn('ℝ jólrendezett a szokásos rendezéssel?'), 0, '(0,1)-nek nincs min'],
    [6, 'Mennyi sup{ 1−e^{-n} : n ≥ 0 }?', 1, '1'],
    [6, yn('Ha a_n → L és a_n ∈ A, akkor L ∈ cl(A)?'), 1, 'lezárt'],
    [6, yn('cl(ℚ) = ℝ?'), 1, 'sűrű'],
    [6, yn('int(ℚ) = ∅ ℝ-ben?'), 1, 'igen'],
    [6, 'Mennyi inf{ x+1/x : x > 0 }?', 2, 'AM-GM'],
    [6, yn('Minden Dedekind-szeletnek van legkisebb felső eleme ℝ-ben?'), 1, 'teljesség'],
    [6, yn('Az |x−y| metrika ℝ-n teljes?'), 1, 'igen'],
    [6, 'Mennyi diam([2, 7]) (átmérő)?', 5, '5'],
    [6, yn('Két diszjunkt nyílt halmaz elválaszthat két pontot ℝ-ben, ha a < b?'), 1, 'Hausdorff'],
];

const szamsorozatok: Row[] = [
    [1, 'a_n = n + 1. Mennyi a_5?', 6, '6'],
    [1, 'a_n = 2n. Mennyi a_7?', 14, '14'],
    [1, 'a_n = 3n − 1. Mennyi a_4?', 11, '11'],
    [1, 'a_n = n². Mennyi a_6?', 36, '36'],
    [1, 'a_n = 1/n. Mennyi a_4?', 0.25, '1/4'],
    [1, 'a_1 = 5, a_{n+1} = a_n + 2. Mennyi a_4?', 11, '5+2+2+2=11'],
    [1, 'a_n = (−1)^n. Mennyi a_3?', -1, '−1'],
    [1, 'a_n = 2^n. Mennyi a_5?', 32, '32'],
    [1, 'Számtani: a_1 = 3, d = 4. Mennyi a_6?', 23, '3+5·4=23'],
    [1, 'Mértani: a_1 = 2, q = 3. Mennyi a_4?', 54, '2·3³=54'],
    [1, 'a_n = n(n+1)/2. Mennyi a_5?', 15, '15'],
    [1, 'a_n = 10 − n. Mennyi a_3?', 7, '7'],
    [1, yn('A (n) sorozat monoton növő?'), 1, 'igen'],
    [1, yn('A (1/n) sorozat monoton csökkenő (n≥1)?'), 1, 'igen'],
    [1, yn('A ((−1)^n) sorozat monoton?'), 0, 'oszcillál'],
    [1, yn('A (n) sorozat korlátos?'), 0, 'nem'],
    [1, yn('A (1/n) sorozat korlátos?'), 1, 'igen, (0,1]'],
    [1, 'a_n = 4, 4, 4, … Mennyi a_100?', 4, 'konstans'],
    [1, 'Fibonacci: F_1=1, F_2=1, F_{n}=F_{n−1}+F_{n−2}. Mennyi F_6?', 8, '1,1,2,3,5,8'],
    [1, 'a_n = n³ − n. Mennyi a_3?', 24, '27−3=24'],
    [2, 'a_n = (2n+1)/(n+1). Mennyi a_3?', 1.75, '7/4'],
    [2, 'a_1=1, a_{n+1}=a_n+n. Mennyi a_5?', 11, '1+1+2+3+4=11'],
    [2, 'a_n = 2n−5. Melyik a legkisebb n≥1, ahol a_n>0?', 3, 'a_3=1'],
    [2, yn('Ha a_n ≤ a_{n+1} minden n-re, a sorozat monoton növő?'), 1, 'igen'],
    [2, yn('Minden konvergens sorozat korlátos?'), 1, 'igen'],
    [2, yn('Minden korlátos sorozat konvergens?'), 0, 'pl. (−1)^n'],
    [2, 'a_n = n + (−1)^n. Mennyi a_4?', 5, '4+1=5'],
    [2, 'Részsorozat: a_n=n, b_k=a_{2k}. Mennyi b_5?', 10, '10'],
    [2, 'a_n = 3^n / 3^{n+1}. Mennyi a_n (minden n)?', 0.333, '1/3'],
    [2, yn('A (n²) sorozat alulról korlátos?'), 1, 'igen'],
    [2, yn('A (−n²) sorozat felülről korlátos?'), 1, 'igen, 0'],
    [2, 'a_n = max{n, 5}. Mennyi a_3?', 5, '5'],
    [2, 'a_n = max{n, 5}. Mennyi a_8?', 8, '8'],
    [2, 'a_n = min{n, 4}. Mennyi a_10?', 4, '4'],
    [2, 'Számtani összeg: a_1=1, d=1, első 10 tag összege?', 55, 'n(n+1)/2'],
    [2, yn('Létezik-e konstans részsorozata ((−1)^n)-nek?'), 1, 'páros indexek: 1'],
    [2, 'a_n = ⌊n/2⌋. Mennyi a_5?', 2, '2'],
    [2, 'a_n = n mod 3 (0,1,2 maradék). Mennyi a_8?', 2, '8=2·3+2'],
    [2, yn('Minden monoton sorozatnak van konvergens részsorozata ℝ-ben?'), 0, 'pl. n → ∞'],
    [2, yn('Minden korlátos sorozatnak van konvergens részsorozata ℝ-ben?'), 1, 'Bolzano–Weierstrass'],
    [3, 'a_n = (n²+1)/(n+1). Mennyi a_1?', 1, '2/2=1'],
    [3, 'Rekurzió: a_1=2, a_{n+1}=3a_n. Mennyi a_4?', 54, '2·3³=54'],
    [3, 'a_n = (−1)^n / n. Mennyi a_5?', -0.2, '−1/5'],
    [3, yn('Ha (a_n) monoton növő és felülről korlátos, konvergens?'), 1, 'igen'],
    [3, yn('Ha (a_n) divergens, akkor korlátlan?'), 0, '(−1)^n'],
    [3, 'b_n = a_{n+1}−a_n, a_n=n². Mennyi b_3?', 7, '16−9=7'],
    [3, 'Harmonikus: H_n = 1+1/2+…+1/n. Mennyi H_4?', 2.083, '1+1/2+1/3+1/4=2,083'],
    [3, 'a_n = n/(n+2). Mennyi a_2?', 0.5, '2/4'],
    [3, yn('A Fibonacci-sorozat korlátos?'), 0, 'nem'],
    [3, 'a_n = 5·(1/2)^{n−1}. Mennyi a_1+a_2+a_3?', 8.75, '5+2.5+1.25'],
    [3, yn('Két konvergens sorozat összege konvergens?'), 1, 'igen'],
    [3, yn('Két divergens sorozat összege mindig divergens?'), 0, 'n + (−n)'],
    [3, 'a_n = √(n²+2n) − n. Mennyi a_2? Három tizedesjegy.', 0.828, '√8−2≈0,828'],
    [3, 'Indexelt max: a_n = (−1)^n n. Mennyi max{a_1,a_2,a_3,a_4}?', 4, '4'],
    [3, yn('Van-e (a_n)-nek szigorúan monoton növő részsorozata, ha a_n=n?'), 1, 'önmaga'],
    [3, yn('Minden sorozatnak van monoton részsorozata?'), 1, 'Erdős–Szekeres / klasszikus tétel'],
    [3, 'a_n = 2n+3, b_n=a_{n}−a_{n−1} (n≥2). Mennyi b_n?', 2, 'állandó differencia'],
    [3, 'Mértani: a_1=81, q=1/3. Mennyi a_5?', 1, '81/81=1'],
    [3, yn('Ha a_{n+1}=a_n, a sorozat konstans?'), 1, 'igen'],
    [3, 'a_n = n! / (n−1)! (n≥1, 0!=1). Mennyi a_6?', 6, 'n'],
    [4, yn('Ha a_n → L, akkor a_{n+1} → L?'), 1, 'eltolás'],
    [4, yn('Ha a_{2n}→L és a_{2n+1}→L, akkor a_n→L?'), 1, 'igen'],
    [4, yn('Ha a_{2n}→1 és a_{2n+1}→−1, akkor a_n konvergens?'), 0, 'nem'],
    [4, 'Cesàro: σ_n = (a_1+…+a_n)/n, a_k=k. Mennyi σ_4?', 2.5, '10/4'],
    [4, yn('Ha a_n konvergens, a Cesàro-közepek is?'), 1, 'igen'],
    [4, yn('Ha a Cesàro-közepek konvergensek, a_n is?'), 0, 'pl. (−1)^n'],
    [4, 'a_n = n^{1/n}. Mennyi a_1?', 1, '1'],
    [4, 'Rekurzió: a_1=1, a_{n+1}=(a_n+2/a_n)/2 (Newton √2). Mennyi a_2?', 1.5, '1.5'],
    [4, yn('Korlátos + monoton ⇒ konvergens ℝ-ben?'), 1, 'igen'],
    [4, 'a_n = (1+1/n)^n. Mennyi a_1?', 2, '2'],
    [4, 'lim inf (−1)^n? ', -1, '−1'],
    [4, 'lim sup (−1)^n?', 1, '1'],
    [4, yn('lim inf a_n ≤ lim sup a_n mindig?'), 1, 'igen'],
    [4, yn('a_n konvergens ⇔ lim inf = lim sup (véges)?'), 1, 'igen'],
    [4, 'a_n = 1, 3, 1, 3, … lim inf?', 1, '1'],
    [4, 'Ugyanez lim sup?', 3, '3'],
    [4, yn('Minden részsorozat konvergens, ha a_n konvergens?'), 1, 'igen, ugyanoda'],
    [4, 'a_n = n sin(π n). Mennyi a_2?', 0, 'sin(2π)=0'],
    [4, yn('Ha |a_n| korlátos, a_n korlátos?'), 1, 'ekvivalens'],
    [4, 'Szorzat: a_n=n, b_n=1/n. Mennyi a_n b_n?', 1, '1'],
    [5, 'a_n = n / 2^n. Mennyi a_4?', 0.25, '4/16'],
    [5, yn('Ha a_n → 0 és (b_n) korlátos, akkor a_n b_n → 0?'), 1, 'igen'],
    [5, yn('Ha a_n → ∞, akkor 1/a_n → 0?'), 1, 'igen (elég nagy n-től ≠0)'],
    [5, 'a_n = (1²+…+n²)/n³. Mennyi a_2?', 0.625, '(1+4)/8=5/8'],
    [5, yn('Ha a_{n+1}−a_n → 0, akkor a_n konvergens?'), 0, 'H_n harmonikus'],
    [5, 'lim inf (1+1/n)^n? Add meg 2.718-t (e).', 2.718, 'e'],
    [5, 'a_n = √(n+1)−√n. Mennyi a_3? Három tizedesjegy.', 0.268, '2−√3≈0,268'],
    [5, yn('Konvergens sorozat részsorozatainak határértéke ugyanaz?'), 1, 'igen'],
    [5, 'a_n = n^2 − (n−1)^2. Mennyi a_10?', 19, '20n−1 at n=10: 19'],
    [5, yn('Ha a_n ≤ b_n ≤ c_n és a_n,c_n → L, akkor b_n → L?'), 1, 'rendőr'],
    [5, 'Rekurzió: a_1=0, a_{n+1}=√(2+a_n). Mennyi a_2? Három tizedesjegy.', 1.414, '√2'],
    [5, yn('Igaz-e, hogy (n!)^{1/n} / n → 1/e?'), 1, 'Stirling'],
    [5, 'a_n = (n+2 choose 2) / n². n=4: C(6,2)/16?', 0.938, '15/16'],
    [5, yn('Minden rekurzív a_{n+1}=f(a_n) sorozat konvergens, ha f folytonos?'), 0, 'pl. f(x)=x+1'],
    [5, 'Páros-páratlan: a_n = n ha páros, −n ha páratlan. Korlátos? (1=igen)', 0, 'nem'],
    [5, 'Ugyanez: van konvergens részsorozata? (1=igen)', 0, 'minden |a_n|→∞'],
    [5, 'a_n = ⌊e·n⌋ − ⌊e·(n−1)⌋ n=1-re: ⌊e⌋?', 2, '⌊2.718⌋=2'],
    [5, yn('Két korlátos sorozat szorzata korlátos?'), 1, 'igen'],
    [5, yn('Két korlátos sorozat hányadosa mindig korlátos?'), 0, 'b_n→0'],
    [5, 'a_n = (n²+n)/(n+1). Mennyi a_4?', 4, '20/5=4'],
    [6, 'Newton √3: a_1=2, a_{n+1}=(a_n+3/a_n)/2. Mennyi a_2?', 1.75, '(2+1.5)/2=1.75'],
    [6, yn('Ha lim inf a_n = +∞, akkor a_n → +∞?'), 1, 'igen'],
    [6, yn('Ha a_n → L és f folytonos L-ben, f(a_n)→f(L)?'), 1, 'igen'],
    [6, 'a_n = n! / n^n. Mennyi a_3?', 0.222, '6/27=2/9≈0,222'],
    [6, yn('Minden korlátos valós sorozatnak van Cauchy-részsorozata?'), 1, 'BW + teljesség'],
    [6, 'lim sup (1+1/n)^{n+1}? 2.718 (e)', 2.718, 'e'],
    [6, yn('a_n = sin n konvergens?'), 0, 'sűrű [−1,1]-ben'],
    [6, 'a_n = (2n)! / (n!)^2 / 4^n  (n=2): C(4,2)/16?', 0.375, '6/16'],
    [6, yn('Ha a_n+b_n konvergens és a_n konvergens, b_n is?'), 1, 'igen'],
    [6, yn('Ha a_n b_n → 0, akkor a_n → 0 vagy b_n → 0?'), 0, 'nem feltétlen'],
    [6, 'a_n = ∏_{k=1}^n (1+1/k). Mennyi a_4?', 5, '(n+1) = 5'],
    [6, yn('A Banach-fixpont: kontrakció teljes téren konvergens iterációt ad?'), 1, 'igen'],
    [6, 'a_n = (n/(n+1))^n. Mennyi a_1?', 0.5, '1/2'],
    [6, yn('Ha a_n ≤ a_{n+1} és a_n → L, akkor a_n ≤ L?'), 1, 'igen'],
    [6, 'Részletösszeg s_n = 1+2+…+n, s_n / n² n=5?', 0.6, '15/25'],
    [6, yn('Minden valós sorozatnak van monoton növő vagy csökkenő végtelen részsorozata?'), 1, 'igen'],
    [6, 'Fibonacci: F_6 / F_5 = ?', 1.6, '8/5=1,6'],
    [6, yn('Korlátos ingadozású (BV) sorozat előáll két monoton különbségeként?'), 1, 'Jordan'],
    [6, 'a_n=√n. Mennyi 4(√4−√3)? Három tizedesjegy.', 1.072, '4(2−√3)≈1,072'],
    [6, yn('Ha minden részsorozatnak van tovább konvergens részsorozata ugyanoda, a_n konvergens?'), 1, 'igen'],
];

const seqHatar: Row[] = [
    [1, 'lim (n→∞) 1/n = ?', 0, '0'],
    [1, 'lim n/(n+1) = ?', 1, '1'],
    [1, 'lim (3n+1)/(n+2) = ?', 3, '3'],
    [1, 'lim 5 = ? (konstans)', 5, '5'],
    [1, 'lim 1/n² = ?', 0, '0'],
    [1, 'lim (2n−4)/(n) = ?', 2, '2'],
    [1, 'lim n/(n²+1) = ?', 0, '0'],
    [1, 'lim (n+3)/(2n) = ?', 0.5, '1/2'],
    [1, 'lim (4n²)/(2n²+1) = ?', 2, '2'],
    [1, yn('lim (−1)^n létezik végesen?'), 0, 'oszcillál'],
    [1, 'lim 1/2^n = ?', 0, '0'],
    [1, 'lim (n²+3n)/n² = ?', 1, '1'],
    [1, 'lim (5n+2)/(10n−1) = ?', 0.5, '1/2'],
    [1, yn('lim n = +∞? (1=igen, divergál +∞-be)'), 1, 'igen'],
    [1, 'lim (1+2/n) = ?', 1, '1'],
    [1, 'lim n·(1/n) = ?', 1, '1'],
    [1, 'lim (3−1/n) = ?', 3, '3'],
    [1, 'lim 100/n = ?', 0, '0'],
    [1, 'lim (n−1)/(n+1) = ?', 1, '1'],
    [1, 'lim 2^{-n}·n^0 = ?', 0, '0'],
    [2, 'lim (n²−1)/(n²+n) = ?', 1, '1'],
    [2, 'lim (2n³+1)/(n³−n) = ?', 2, '2'],
    [2, 'lim √n / n = ?', 0, '0'],
    [2, 'lim (√(n²+n) − n)? Három tizedesjegy (1/2).', 0.5, '1/2'],
    [2, 'lim n(√(1+1/n)−1)? Három tizedes.', 0.5, '1/2'],
    [2, 'lim (1+1/n)^n ? Három tizedes (e).', 2.718, 'e'],
    [2, 'lim n^{1/n} = ?', 1, '1'],
    [2, 'lim (n+1)! / (n · n!) = ?', 1, '(n+1)/n → 1'],
    [2, 'lim (3^n + 2^n)/3^n = ?', 1, '1'],
    [2, 'lim n sin(1/n) = ? (1/n rad)', 1, '1'],
    [2, 'lim n² (1/n − 1/(n+1)) = ?', 1, 'n²/(n(n+1))→1'],
    [2, 'lim (2n+3)/(5n−7) = ?', 0.4, '2/5'],
    [2, yn('lim (n²) véges?'), 0, '+∞'],
    [2, 'lim (1−1/n)^n ? Három tizedes (1/e).', 0.368, '1/e'],
    [2, 'lim (n²+3n+2)/(n+1) / n  = lim (n+2)/n = ?', 1, '1'],
    [2, yn('lim (n³−8)/(n−2) véges?'), 0, 'n²-szerű'],
    [2, 'lim (4n+1)/(2n+8) = ?', 2, '2'],
    [2, 'lim √(4n²+n)/n = ?', 2, '2'],
    [2, 'lim (e^{1/n}) = ?', 1, '1'],
    [2, 'lim ln(n+1)−ln n = ?', 0, 'ln(1+1/n)→0'],
    [3, 'lim n² / 2^n = ?', 0, '0'],
    [3, 'lim n! / n^n = ?', 0, '0'],
    [3, 'lim (√(n+1)−√n)·√n = ? Három tizedes (1/2).', 0.5, '1/2'],
    [3, 'lim (1+2/n)^n ? Három tizedes (e²).', 7.389, 'e²'],
    [3, 'lim n (ln(n+1)−ln n) = ?', 1, 'n ln(1+1/n)→1'],
    [3, 'lim (2n)! / (n! n!) / 4^n  n→∞? (centr. binom /4^n →0)', 0, '0'],
    [3, 'lim (n^3+n)/(2n^3−1) = ?', 0.5, '1/2'],
    [3, yn('lim sin n létezik?'), 0, 'nem'],
    [3, 'lim n(1−cos(1/n))? Három tizedes. n·(1/2n²)=1/(2n)→0', 0, '0'],
    [3, 'lim (tan(1/n))/(1/n) = ?', 1, '1'],
    [3, 'lim (a_{n+1}/a_n) ha a_n=2^n / n!  → ?', 0, '0'],
    [3, 'lim (√n sin(1/√n)) = ?', 1, '1'],
    [3, 'lim C(n+2, 2) / n² = ?', 0.5, '(n+2)(n+1)/(2n²) → 1/2'],
    [3, 'lim (3n²−n)/(6n²+5) = ?', 0.5, '1/2'],
    [3, 'lim n^{1/n²} = ?', 1, '1'],
    [3, yn('Ha |a_n|→0, akkor a_n→0?'), 1, 'igen'],
    [3, 'lim (2^{n+1} + 3^{n})/3^{n+1} = ?', 0.333, '1/3'],
    [3, 'lim (ln n)/n = ?', 0, '0'],
    [3, 'lim √(n² + 5n) / n = ?', 1, '1'],
    [3, yn('lim n / ln n véges?'), 0, '+∞'],
    [4, 'lim (1+1/n)^{n+1} ? 2.718', 2.718, 'e'],
    [4, 'lim n (2^{1/n} − 1) = ? Három tizedesjegy (ln 2).', 0.693, 'ln 2'],
    [4, 'lim (e^{1/n} − 1)·n = ?', 1, '1'],
    [4, 'lim n² (cos(1/n)−1)? −1/2 = −0.5', -0.5, 'n²(−1/(2n²))'],
    [4, 'lim (∛(n³+n²) − n) = ? Három tizedes (1/3).', 0.333, '1/3'],
    [4, yn('Ha a_n→L≠0, akkor 1/a_n → 1/L?'), 1, 'igen'],
    [4, 'lim (n arctan(1/n)) = ?', 1, '1'],
    [4, 'lim (sinh(1/n))/(1/n) = ?', 1, '1'],
    [4, 'lim (n!)^{1/n} / n ? 1/e ≈ 0.368', 0.368, '1/e'],
    [4, 'lim (1/n) ∑_{k=1}^n (k/n) = ? (integrál x dx = 1/2)', 0.5, '1/2'],
    [4, 'lim (1−cos(1/n))/(1/n)² = ?', 0.5, '1/2'],
    [4, yn('Rendőr-elv: a_n≤b_n≤c_n, a_n,c_n→L ⇒ b_n→L?'), 1, 'igen'],
    [4, 'lim q^n ha |q|<1?', 0, '0'],
    [4, yn('lim q^n véges, ha q=−1?'), 0, 'oszcillál'],
    [4, 'lim (n+1)^3 − n^3  / n² ? (3n²+…)/n² → 3', 3, '3'],
    [4, 'lim √(n+√n) − √n ? 0', 0, '0'],
    [4, 'lim n (√(1 + 1/n²) − 1) = ?', 0, '∼ 1/(2n) → 0'],
    [4, 'lim (2n+1 choose n) / (2n choose n) = ?  (2n+1)/(n+1) → 2', 2, '2'],
    [4, yn('Ha a_n→∞ és b_n→∞, a_n−b_n → ∞?'), 0, 'nem feltétlen'],
    [4, 'lim n^2 / (n+1)!  = 0', 0, '0'],
    [5, 'lim n ( e^{1/n} − 1 − 1/n ) ? 1/(2n) · n → 0.5', 0.5, '1/2'],
    [5, 'lim (tan(1/n) − 1/n) · n^3 ? 1/3 ≈ 0.333', 0.333, '1/3'],
    [5, 'lim (∑_{k=1}^n k)/n² = ?', 0.5, '1/2'],
    [5, 'lim (∑_{k=1}^n k²)/n³ = ?', 0.333, '1/3'],
    [5, 'lim n^{1/ln n}  (n>1)? e', 2.718, 'e'],
    [5, yn('Stolz–Cesàro: a_n/b_n → L ha Δa/Δb → L (b szig. növő, →∞)?'), 1, 'igen'],
    [5, 'lim (H_n − ln n)? ≈ γ ≈ 0.577', 0.577, 'Euler-Mascheroni'],
    [5, 'lim n² sin(1/n²) = ?', 1, '1'],
    [5, 'lim (∛n+1 − ∛n)·n^{2/3} = ? 1/3', 0.333, '1/3'],
    [5, yn('Ha a_n→0+, ln a_n → −∞?'), 1, 'igen'],
    [5, 'lim (1+1/n²)^n = ?', 1, '1'],
    [5, 'lim (1+1/n²)^{n²} = ?  e', 2.718, 'e'],
    [5, 'lim n² ( √(1+1/n) − √(1−1/n) − 1/n ) = ?', 0, '∼ 1/(8n) → 0'],
    [5, 'lim (arcsin(1/n))/(1/n) = ?', 1, '1'],
    [5, 'lim n (2^{1/n} − 1) = ln 2 ≈ 0.693', 0.693, 'ln 2'],
    [5, yn('Ha a_n → L és b_n → M, a_n^{b_n} → L^M (L>0)?'), 1, 'igen'],
    [5, 'lim (n ln(1+1/n)) = ?', 1, '1'],
    [5, 'lim (cos(1/n))^n = ?', 1, '1'],
    [5, 'lim n³ (sin(1/n) − 1/n + 1/(6n³)) = ?', 0, 'O(1/n²) → 0'],
    [5, yn('lim inf a_n = lim a_n ha a_n konvergens?'), 1, 'igen'],
    [6, 'lim (n!)^{1/n²} = ?', 1, '1'],
    [6, 'lim (∑_{k=1}^n 1/k²) ? π²/6 ≈ 1.645', 1.645, 'ζ(2)'],
    [6, 'lim n (1 − (1−1/n)^n ) ? 1 − 1/e ≈ 0.632', 0.632, '1−1/e'],
    [6, 'lim (ln n)^{1/n} = ?', 1, '1'],
    [6, 'lim (sin n)/n = ?', 0, '0'],
    [6, yn('Ha a_n→L, akkor (a_1+…+a_n)/n → L?'), 1, 'Cesàro'],
    [6, 'lim n² (2^{1/n} − 1 − (ln 2)/n)? (ln 2)²/2 ≈ 0.240', 0.24, '(ln 2)²/2'],
    [6, 'lim (∏_{k=1}^n (1+1/k))^{1/n} = lim (n+1)^{1/n} = ?', 1, '1'],
    [6, 'lim √n (√(n+1)−√n) = ? 1/2', 0.5, '1/2'],
    [6, yn('Ha a_n > 0 és a_{n+1}/a_n → L<1, akkor a_n→0?'), 1, 'arány'],
    [6, 'lim (e − (1+1/n)^n)? → 0, de pozitív. Add meg 0-t (határérték).', 0, '0'],
    [6, 'lim n ((1+1/n)^n − e)? −e/2 ≈ −1.359', -1.359, '−e/2'],
    [6, 'lim (cos n)/n = ?', 0, '0'],
    [6, yn('lim (tan n)/n véges?'), 0, 'tan n nem korlátos viselkedés'],
    [6, 'lim (H_n^{(2)}) n→∞ = ζ(2) ≈ 1.645', 1.645, 'π²/6'],
    [6, 'lim n·a_n ha a_n=1/(n ln n) (n≥2)? 0? n/(n ln n)=1/ln n → 0', 0, '0'],
    [6, yn('Ha a_n = o(1/n), akkor n a_n → 0?'), 1, 'definíció'],
    [6, 'lim (C(2n,n))^{1/n} / 4 = ? 1', 1, '1'],
    [6, 'lim (ln ln n)/ln n  (n≥3) = ?', 0, '0'],
    [6, yn('lim n (n^{1/n}−1) véges?'), 0, '∼ ln n → ∞'],
];

const BANKS: Record<string, Row[]> = {
    'a1-valos-szamok': valos,
    'a1-komplex': komplex as Row[],
    'a1-szamsorozatok': szamsorozatok,
    'a1-seq-hatarertek': seqHatar,
    'a1-cauchy': cauchy as Row[],
    'a1-numerikus-sorok': numerikusSorok as Row[],
    'a1-konv-kriteriumok': konvKrit as Row[],
    'a1-absz-felteteles': abszFelt as Row[],
    'a1-fv-hatarertek': fvHatar as Row[],
    'a1-nevezetes-lim': nevezetes as Row[],
    'a1-folytonossag': folytonossag as Row[],
    'a1-folytonos-tetelek': folytonosTetelek as Row[],
};

function assertSixByTwenty(topicId: string, list: Question[]): void {
    const stages = [1, 2, 3, 4, 5, 6].map((s) => list.filter((q) => q.stage === s).length);
    if (list.length !== 120 || stages.some((n) => n !== 20)) {
        throw new Error(`${topicId}: ${list.length} cards stages=${stages.join(',')}`);
    }
}

export function getAnalizis1PracticeQuestions(topicId: string): Question[] | null {
    const rows = BANKS[topicId.toLowerCase()];
    if (!rows) return null;
    const list = bank(rows);
    assertSixByTwenty(topicId, list);
    return list;
}

export function getAllAnalizis1Banks(): Record<string, Question[]> {
    const out: Record<string, Question[]> = {};
    for (const id of ANALIZIS1_TOPIC_IDS) {
        out[id] = getAnalizis1PracticeQuestions(id) || [];
    }
    return out;
}

