import type { A1Row } from './analizis1LevelsB';

function yn(text: string): string {
    return `${text}\n(1 = igen, 0 = nem)`;
}

export const konvKrit: A1Row[] = [
    [1, yn('Arányteszt: lim |a_{n+1}/a_n| < 1 ⇒ ∑ konvergens?'), 1, 'igen'],
    [1, yn('Arányteszt: lim |a_{n+1}/a_n| > 1 ⇒ ∑ divergens?'), 1, 'igen'],
    [1, yn('Arányteszt: lim = 1 esetén dönt?'), 0, 'határeset'],
    [1, yn('Gyökteszt: lim sup |a_n|^{1/n} < 1 ⇒ konvergens?'), 1, 'igen'],
    [1, yn('Gyökteszt: lim sup > 1 ⇒ divergens?'), 1, 'igen'],
    [1, yn('Összehasonlító teszt pozitív tagokra érvényes?'), 1, 'igen'],
    [1, yn('Limeszes összehasonlítás: a_n/b_n→L∈(0,∞) ⇒ ugyanaz a konvergencia?'), 1, 'igen'],
    [1, yn('Integrálteszt: monoton csökkenő f≥0, ∑f(n) ⇔ ∫^∞ f?'), 1, 'igen'],
    [1, yn('Leibniz: a_n↓0 ⇒ ∑ (−1)^n a_n konvergens?'), 1, 'igen'],
    [1, yn('p-sor konvergens, ha p>1?'), 1, 'igen'],
    [1, yn('p-sor konvergens, ha p=1?'), 0, 'harmonikus'],
    [1, yn('Geometriai |q|<1 konvergens?'), 1, 'igen'],
    [1, 'a_n=(1/2)^n. lim |a_{n+1}/a_n| = ?', 0.5, '1/2'],
    [1, 'a_n=1/n!. lim |a_{n+1}/a_n| = ?', 0, '0'],
    [1, 'a_n=n/2^n. lim |a_{n+1}/a_n| = ?', 0.5, '1/2'],
    [1, yn('∑ 1/n² az arányteszt szerint konvergens (lim=1)?'), 0, 'lim=1, nem dönt; más teszt igen'],
    [1, yn('∑ 1/n² konvergens (p-sor)?'), 1, 'igen'],
    [1, yn('∑ 2^n / n! konvergens (arány)?'), 1, 'lim=0<1'],
    [1, yn('∑ n! / n^n konvergens (arány/gyök)?'), 1, 'igen'],
    [1, yn('∑ n^n / n! konvergens?'), 0, 'tagok → ∞'],
    [2, yn('Cauchy-kondenzáció: a_n↓0, ∑a_n ⇔ ∑ 2^k a_{2^k}?'), 1, 'igen'],
    [2, yn('∑ 1/(n ln n) n≥2 az integrálteszt szerint konvergens?'), 0, 'divergens'],
    [2, yn('∑ 1/(n (ln n)²) n≥2 konvergens?'), 1, 'igen'],
    [2, yn('Dirichlet: s_n=∑_{k=1}^n a_k korlátos, b_n↓0 ⇒ ∑ a_n b_n konv.?'), 1, 'igen'],
    [2, yn('Abel: ∑ a_n konv., (b_n) monoton korlátos ⇒ ∑ a_n b_n konv.?'), 1, 'igen'],
    [2, yn('∑ (sin n)/n konvergens (Dirichlet)?'), 1, 'igen'],
    [2, yn('∑ (sin n)/n abszolút konvergens?'), 0, 'harmonikus jelleg'],
    [2, yn('Raabe-teszt az arány=1 esetet finomítja?'), 1, 'igen'],
    [2, yn('Gauss-teszt még finomabb, mint a Raabe?'), 1, 'igen'],
    [2, yn('Összehasonlítás: 0≤a_n≤b_n, ∑b_n konv. ⇒ ∑a_n konv.?'), 1, 'igen'],
    [2, yn('0≤a_n≤b_n, ∑a_n div. ⇒ ∑b_n div.?'), 1, 'igen'],
    [2, 'a_n=n²/3^n. lim |a_{n+1}/a_n| = ? Három tizedes.', 0.333, '1/3'],
    [2, yn('∑ n²/3^n konvergens?'), 1, 'arány 1/3<1'],
    [2, yn('∑ (n+1)/(n+2) · 1/2^n konvergens?'), 1, 'arány 1/2'],
    [2, yn('Gyök: lim n^{1/n}=1, így ∑ 1/n gyöktesztje nem dönt?'), 1, 'lim=1'],
    [2, yn('∑ (1/2 + 1/n)^n konvergens?'), 1, 'gyök → 1/2<1'],
    [2, yn('∑ (3/2)^n / n² konvergens?'), 0, 'tagok nem →0'],
    [2, yn('Integrál: ∫_2^∞ dx/(x ln x) divergens?'), 1, 'ln ln x'],
    [2, yn('Weierstrass M: |u_n|≤M_n, ∑M_n konv. ⇒ ∑u_n absz. konv.?'), 1, 'igen'],
    [2, yn('Hányadosteszt erősebb a gyöktesztnél (ha az arány létezik, egyenlő a gyökkel)?'), 0, 'gyök általánosabb; lim arány = lim gyök ha mindkettő létezik'],
    [3, yn('Ha lim |a_{n+1}/a_n|=L, akkor lim |a_n|^{1/n}=L (ha léteznek)?'), 1, 'igen'],
    [3, yn('∑ n! x^n konvergens |x|>0-ra?'), 0, 'R=0'],
    [3, yn('∑ x^n / n! konvergens minden x-re?'), 1, 'R=∞'],
    [3, yn('∑ x^n konvergenciasugara 1?'), 1, 'igen'],
    [3, yn('∑ x^n / n konvergenciasugara 1?'), 1, 'igen'],
    [3, yn('∑ x^n / n x=−1-en konvergens?'), 1, '−ln2'],
    [3, yn('∑ x^n / n x=1-en konvergens?'), 0, 'harmonikus'],
    [3, yn('∑ x^n / n² x=±1-en konvergens?'), 1, 'igen'],
    [3, 'R: c_n=2^n, 1/R = lim |c_n|^{1/n} = ?', 2, '2, tehát R=1/2'],
    [3, 'Ugyanez: R = ?', 0.5, '1/2'],
    [3, yn('Cauchy-sűrítés  a_n=1/n: 2^k · 1/2^k = 1 divergens?'), 1, 'igen'],
    [3, yn('a_n=1/n²: 2^k / 4^k = (1/2)^k konvergens?'), 1, 'igen'],
    [3, yn('Kummer, Bertrand további arány-finomítások?'), 1, 'igen'],
    [3, yn('Ha a_n ~ 1/n, ∑ a_n divergens?'), 1, 'igen'],
    [3, yn('Ha a_n = o(1/n^{1+ε}) ε>0, ∑ konvergens?'), 1, 'igen'],
    [3, yn('Aszimptotika a_n ∼ b_n >0 ⇒ ugyanaz a konvergencia?'), 1, 'igen'],
    [3, yn('∑ (√(n²+1)−n) konvergens?'), 0, '∼ 1/(2n)'],
    [3, yn('∑ (√(n²+1)−n − 1/(2n)) konvergens?'), 1, '∼ −1/(8n³)'],
    [3, yn('Logaritmikus teszt: ln(1/a_n)/ln n → p>1 ⇒ konvergens?'), 1, 'igen'],
    [3, yn('∑ e^{−n} n^{100} konvergens?'), 1, 'arány → e^{−1}'],
    [4, yn('Gauss-teszt: a_n/a_{n+1} = 1 + μ/n + O(1/n^λ), λ>1, konv. ⇔ μ>1?'), 1, 'igen'],
    [4, yn('Raabe: n(a_n/a_{n+1}−1) → L, konv. ha L>1?'), 1, 'igen'],
    [4, yn('A centralis binomiális hatványsor sugara 1/4?'), 1, 'igen'],
    [4, yn('Hypergeometrikus ₂F₁ konvergenciája |z|<1?'), 1, 'igen'],
    [4, yn('Integrálteszt nem alkalmazható, ha f nem monoton?'), 1, 'a klasszikus forma monotonitást kér'],
    [4, yn('Összehasonlítás csak nemnegatív tagokra megy közvetlenül?'), 1, 'igen'],
    [4, yn('Abszolút konvergencia ⇒ konvergencia?'), 1, 'igen ℝ-ben'],
    [4, yn('Konvergencia ⇒ abszolút konvergencia?'), 0, 'feltételes'],
    [4, yn('∑ (−1)^n / n^{0.9} Leibniz?'), 1, 'igen, csökken →0'],
    [4, yn('∑ (−1)^n / n^{0.9} abszolút?'), 0, 'p<1'],
    [4, yn('Dirichlet alkalmazható a_n=(−1)^n, b_n=1/ln n (n≥2)?'), 1, 's_n korlátos, b↓0'],
    [4, yn('∑ (−1)^n ln n / n konvergens?'), 1, 'Dirichlet/Abel'],
    [4, yn('Dini: ha f_n↑f folytonos [a,b]-n, egyenletes a konvergencia?'), 1, 'igen'],
    [4, yn('Egyenletes konvergencia tesztje a Cauchy-kritérium egyenletesen?'), 1, 'igen'],
    [4, yn('∑ 1/(n log n log log n) n≥N_0 divergens?'), 1, 'integrál'],
    [4, yn('Ermakoff, Cauchy-sűrítés általánosításai léteznek?'), 1, 'igen'],
    [4, 'lim |a_{n+1}/a_n| a_n= (n+1)/(n 2^n) → ?', 0.5, '1/2'],
    [4, yn('Ha gyök lim sup=1 és arány nem létezik, a sor lehet konvergens is divergens is?'), 1, 'igen'],
    [4, yn('∑ (n ln n)^{-1} (n≥2) divergens?'), 1, 'igen'],
    [4, yn('Összehasonlítás ℓ^{p}: a∈ℓ^{1} ⇒ a∈ℓ^{2} véges mérték? Sorokra: ℓ¹⊂ℓ² hamis. ∑|a_n|<∞ ⇒ ∑ a_n² <∞?'), 1, 'igen, a_n→0'],
    [5, yn('Hadamard-formula mindig megadja R-t?'), 1, 'igen (lehet 0 vagy ∞)'],
    [5, yn('Arányteszt hatványsorra: R = lim |c_n/c_{n+1}| ha létezik?'), 1, 'igen'],
    [5, yn('A körön a gyök/arány nem dönti el a konvergenciát?'), 1, 'igen'],
    [5, yn('Abel-tétel: konvergencia x=1-en ⇒ folytonos kiterjesztés balról?'), 1, 'igen'],
    [5, yn('Tauber: o(1/n) + Abel-szummálható ⇒ konvergens?'), 1, 'igen'],
    [5, yn('∑ n^{-1} (log n)^{-2} n≥2 konvergens?'), 1, 'integrál p=2>1'],
    [5, yn('Bertrand: ∑ 1/(n ln n (ln ln n)^p) konv. ⇔ p>1?'), 1, 'igen'],
    [5, yn('Cauchy-szorzat két konvergens sornak lehet divergens?'), 1, 'igen (nem abszolút)'],
    [5, yn('Mertens tétele abszolút×konvergens szorzatra?'), 1, 'igen'],
    [5, yn('∑ a_n b_n, ha a∈ℓ², b∈ℓ², abszolút konvergens?'), 1, 'CS'],
    [5, yn('Hölder: ℓ^p · ℓ^q ⊂ ℓ¹, 1/p+1/q=1?'), 1, 'igen'],
    [5, yn('Integrálteszt Cauchy-féle sűrítéssel ekvivalens monoton esetben?'), 1, 'hasonló erősség'],
    [5, yn('∑ (sin n²)/n konvergens?'), 1, 'Dirichlet-szerű / Weyl'],
    [5, yn('∑ (sin n²)/√n viselkedése nehezebb (Carleson stb.)?'), 1, 'igen'],
    [5, yn('Raabe L=1 határeset, Gauss kellhet?'), 1, 'igen'],
    [5, yn('Pozitív tagú sornál a részletösszeg vagy konv. vagy +∞?'), 1, 'igen'],
    [5, yn('Alternáló sornál a maradék jele és |R_n|≤a_{n+1}?'), 1, 'Leibniz-maradék'],
    [5, yn('Ha a teszt „nem dönt”, a sor státusza ismeretlen a tesztből?'), 1, 'igen'],
    [5, yn('Több teszt kombinálható (pl. abszolút + Leibniz)?'), 1, 'igen'],
    [5, 'Centralis binomiális / 4^n. lim |a_{n+1}/a_n| = ?', 1, '1'],
    [6, yn('Stolz az arányteszt diszkrét L\'Hospitalja?'), 1, 'hasonló szellem'],
    [6, yn('Kummer-teszt általánosítja a Raabe-t?'), 1, 'igen'],
    [6, yn('Gauss-teszt hypergeometrikus sorokra klasszikus?'), 1, 'igen'],
    [6, yn('Olver, Darboux aszimptotika a tagokra tesztet ad?'), 1, 'igen'],
    [6, yn('∑ (ln n)^k / n^p konv. ⇔ p>1, bármely k?'), 1, 'igen'],
    [6, yn('∑ n^k / q^n konv. |q|>1, bármely k?'), 1, 'igen'],
    [6, yn('A gyökteszt finomabb az aránynál, ha az arány nem létezik?'), 1, 'igen'],
    [6, yn('Példa: a_n=2^{−n} (n páros), 3^{−n} (n páratlan): arány nem létezik, gyök dönt?'), 1, 'gyök 1/2 ill 1/3, limsup 1/2<1'],
    [6, yn('∑ a_n divergens, ha lim sup |a_n|^{1/n} > 1?'), 1, 'igen, a_n ↛ 0'],
    [6, yn('Egyenletes teszt tartományon: Weierstrass M?'), 1, 'igen'],
    [6, yn('Dirichlet egyenletes: S_n egyenletesen korlátos, b_n↓0 egyenletesen?'), 1, 'igen'],
    [6, yn('Abel egyenletes tétel hatványsorokra a zárt sugáron (ha konv.)?'), 1, 'igen'],
    [6, yn('Pringsheim: a_n↓, ∑a_n konv. ⇒ n a_n→0?'), 1, 'igen'],
    [6, yn('n a_n→0 nem elégséges (1/(n ln n))?'), 1, 'igen'],
    [6, yn('Összehasonlítás integrállal és sűrítéssel ugyanazt adja p-sorra?'), 1, 'igen'],
    [6, yn('A zeta(s) éppen a p-sor s>1?'), 1, 'igen'],
    [6, yn('Kondenzáció logaritmikus skálára is működik?'), 1, 'igen'],
    [6, yn('Numerikus teszt (részletösszeg) nem helyettesíti a bizonyítást, de sejtést ad?'), 1, 'igen'],
    [6, yn('Ha minden klasszikus teszt határesetet ad, kell aszimptotika?'), 1, 'igen'],
    [6, yn('Abszolút konvergencia tesztelhető |a_n|-re a fenti tesztekkel?'), 1, 'igen'],
];

export const abszFelt: A1Row[] = [
    [1, yn('Ha ∑ |a_n| konvergens, ∑ a_n konvergens?'), 1, 'abszolút ⇒ konvergens'],
    [1, yn('Ha ∑ a_n konvergens, ∑ |a_n| konvergens?'), 0, 'feltételes ellenpélda'],
    [1, yn('∑ (−1)^{n+1}/n abszolút konvergens?'), 0, 'harmonikus'],
    [1, yn('∑ (−1)^{n+1}/n konvergens?'), 1, 'Leibniz'],
    [1, yn('∑ (−1)^{n+1}/n² abszolút konvergens?'), 1, 'p=2'],
    [1, yn('∑ (−1)^n / √n konvergens?'), 1, 'Leibniz'],
    [1, yn('∑ (−1)^n / √n abszolút?'), 0, 'p=1/2'],
    [1, yn('Geometriai ∑ (−1/2)^n abszolút konvergens?'), 1, '|q|=1/2'],
    [1, yn('Feltételes konvergencia = konvergens, de nem abszolút?'), 1, 'definíció'],
    [1, yn('Abszolút konvergens sor átrendezése ugyanazt az összeget adja?'), 1, 'igen'],
    [1, yn('Feltételesen konvergens sor átrendezése megváltoztathatja az összeget?'), 1, 'Riemann'],
    [1, yn('Ha a_n≥0, konvergencia = abszolút konvergencia?'), 1, 'igen'],
    [1, yn('∑ sin n / n² abszolút?'), 1, '|sin n|≤1, p=2'],
    [1, yn('∑ sin n / n abszolút?'), 0, 'nem'],
    [1, yn('∑ sin n / n konvergens?'), 1, 'Dirichlet'],
    [1, '∑ |q|^n konvergens, ha |q|=0.4? (1=igen)', 1, 'igen'],
    [1, yn('Véges módosítás az abszolút konvergenciát megváltoztatja?'), 0, 'nem'],
    [1, yn('∑ (−1)^n konvergens?'), 0, 'a_n ↛ 0'],
    [1, yn('∑ (−1)^n / n! abszolút?'), 1, 'e'],
    [1, yn('ℓ¹ sorozat abszolút konvergens sor?'), 1, 'igen'],
    [2, yn('Riemann-átrendezési tétel: bármely valós összeg elérhető?'), 1, 'igen'],
    [2, yn('Abszolút konvergens Cauchy-szorzata abszolút konvergens?'), 1, 'igen'],
    [2, yn('Két feltételesen konvergens sor Cauchy-szorzata lehet divergens?'), 1, 'igen'],
    [2, yn('Mertens: abszolút × konvergens ⇒ a szorzat konvergens?'), 1, 'igen'],
    [2, yn('∑ (−1)^n / ln n (n≥2) konvergens?'), 1, 'Leibniz'],
    [2, yn('∑ (−1)^n / ln n abszolút?'), 0, '∫ dx/(x ln x)'],
    [2, yn('Ha ∑ a_n abszolút, ∑ a_n b_n abszolút, ha (b_n) korlátos?'), 1, 'igen'],
    [2, yn('Ha ∑ a_n feltételes, ∑ a_n / n abszolút lehet?'), 1, 'pl. (−1)^n /√n · 1/n'],
    [2, yn('Pozitív és negatív rész külön divergens feltételes sornál?'), 1, 'igen'],
    [2, yn('∑ a_n^+ = +∞ és ∑ a_n^− = +∞ feltételes konvergenciánál?'), 1, 'igen'],
    [2, yn('Sierpiński: átrendezés adott lim inf / lim sup részletösszegre?'), 1, 'igen'],
    [2, yn('Komplex sor abszolút konvergenciája ⇔ a valós és képzetes abszolút?'), 1, 'ekvivalens a modulo-val'],
    [2, yn('∑ z^n / n |z|=1, z≠1 konvergens?'), 1, 'Dirichlet / Abel'],
    [2, yn('∑ z^n / n |z|=1 abszolút, z≠1?'), 0, 'csak z=1-en abszolút sem, és |z|=1-en |z^n/n|=1/n'],
    [2, yn('∑ z^n / n² a zárt egységkörön abszolút?'), 1, 'igen'],
    [2, yn('Unconditional convergence Banach-térben = minden átrendezés konvergens?'), 1, 'igen'],
    [2, yn('ℝ-ben unconditional ⇔ abszolút?'), 1, 'igen'],
    [2, yn('Végtelen dimenzióban van konvergens, nem abszolút sor?'), 1, 'igen'],
    [2, yn('∑ (−1)^n / n^{1/3} feltételes?'), 1, 'Leibniz, p<1'],
    [2, yn('∑ (−1)^n / n^{3} abszolút?'), 1, 'p=3'],
    [3, yn('Dvoretzky–Rogers: végtelen dimenzióban van konvergens nem abszolút sor?'), 1, 'igen'],
    [3, yn('Orlicz: abszolút konvergencia karakterizáció Banachban?'), 1, 'igen'],
    [3, yn('Átrendezés nem változtatja az abszolút konvergens összegét C-ben?'), 1, 'igen'],
    [3, yn('Lévy–Steinitz: ℝ^n-ben az átrendezési összegek affin altér?'), 1, 'igen'],
    [3, yn('ℝ-ben ez az altér pont vagy egész ℝ?'), 1, 'abszolút: pont, feltételes: ℝ'],
    [3, yn('∑ a_n abszolút ⇔ ∑ |Re a_n| és ∑ |Im a_n| konvergens?'), 1, 'igen'],
    [3, yn('Weierstrass M abszolút és egyenletes konvergenciát ad?'), 1, 'igen'],
    [3, yn('Pontonként feltételesen konvergens függvénysor lehet egyenletes?'), 1, 'ritka, de a fogalmak külön'],
    [3, yn('∑ (−1)^n x^n / n  (−1,1)-en abszolút?'), 1, '|x|<1'],
    [3, yn('Ugyanez x=1-en feltételes?'), 1, 'ln2'],
    [3, yn('Ugyanez x=−1-en divergens?'), 1, '−harmonikus'],
    [3, yn('Dirichlet-teszt feltételes konvergenciát adhat abszolút nélkül?'), 1, 'igen'],
    [3, yn('Ha ∑ |a_n| div. és a_n nem vált előjelet, ∑ a_n div.?'), 1, 'igen (előjelállandó)'],
    [3, yn('Csak véges sok negatív tag: konvergencia = abszolút (majdnem)?'), 1, 'igen'],
    [3, yn('∑ a_n b_n, Abel-szummáció megőrizheti a feltételességet?'), 1, 'lehet'],
    [3, yn('Cauchy-szorzat feltételes sornak nem feltétlen konvergens?'), 1, 'igen'],
    [3, yn('∑ (sin n)/n feltételes?'), 1, 'konvergens, nem abszolút'],
    [3, yn('∑ (cos n)/n konvergens?'), 1, 'Dirichlet'],
    [3, yn('∑ (cos n)/n abszolút?'), 0, 'nem'],
    [3, yn('Riemann tétel csak valós sorokra szól a „bármely összeg” formában?'), 1, 'igen, ℝ'],
    [4, yn('Ha ∑ a_n abszolút és (b_n)→b, ∑ a_n b_n abszolút?'), 1, 'korlátos szorzó'],
    [4, yn('Schur: mátrix akkor viszi ℓ¹-et ℓ¹-be, ha oszlopok egyenletesen ℓ¹?'), 1, 'igen'],
    [4, yn('∑ ε_n / n majdnem biztosan feltételes (Rademacher)?'), 1, 'igen, nem abszolút, de konv. m.b.'],
    [4, yn('Khintchine–Kolmogorov: független, var összeg <∞ ⇒ m.b. konv.?'), 1, 'igen'],
    [4, yn('Háromsoros tétel (Kolmogorov) a m.b. konvergenciára?'), 1, 'igen'],
    [4, yn('Abszolút konvergens numerikus sor maradéka ≤ a farok ∑_{k>n}|a_k|?'), 1, 'igen'],
    [4, yn('Leibniz-maradék |R_n|≤a_{n+1}?'), 1, 'igen'],
    [4, yn('Átrendezés abszolút sornál a maradékot is kontrollálja?'), 1, 'igen'],
    [4, yn('Feltételes sornál a részletösszeg oszcillálhat az összeg körül?'), 1, 'igen'],
    [4, yn('∑ (−1)^n / n^{p} abszolút ⇔ p>1?'), 1, 'igen'],
    [4, yn('∑ (−1)^n / n^{p} konvergens ⇔ p>0?'), 1, 'Leibniz p>0'],
    [4, yn('p=0: ∑ (−1)^n divergens?'), 1, 'igen'],
    [4, yn('Komplex hatványsor belsejében abszolút a konvergencia?'), 1, 'igen'],
    [4, yn('A konvergenciakör peremén lehet feltételes?'), 1, 'igen'],
    [4, yn('Egyenletes abszolút konvergencia ⇒ egyenletes konvergencia?'), 1, 'igen'],
    [4, yn('Egyenletes konvergencia ⇒ abszolút?'), 0, 'nem'],
    [4, yn('∑ (−1)^n x^n  (−1,1)-en abszolút?'), 1, '|x|<1'],
    [4, yn('Fourier-sor lehet pontonként konvergens abszolút nélkül?'), 1, 'igen'],
    [4, yn('Parseval: l2 nem feltetlenul l1 egyutthatok?'), 1, '1/n pelda'],
    [4, yn('Unconditional basis ⇒ az együttható-sor unconditional?'), 1, 'igen'],
    [5, yn('Ortonormált sor ∑ ⟨f,e_n⟩ e_n L²-ben mindig konvergens?'), 1, 'igen (Bessel/Riesz–Fischer)'],
    [5, yn('Ugyanez abszolút L²-normában? (∑ ||c_n e_n|| = ∑|c_n|) nem feltétlen véges?'), 1, 'ℓ² nem ℓ¹'],
    [5, yn('ℝ-ben a norma-konvergencia a numerikus abszolút?'), 1, '1 dim'],
    [5, yn('Steinitz ℝ²-ben az átrendezési halmaz síkbeli?'), 1, 'lehet sík, egyenes, pont'],
    [5, yn('Végtelen dimenzióban az átrendezési halmaz lehet az egész tér?'), 1, 'igen'],
    [5, yn('Ha ∑ ||x_n|| <∞ Banachban, a sor abszolút és konvergens?'), 1, 'igen'],
    [5, yn('Konvergens Banach-sor mindig abszolút?'), 0, 'nem'],
    [5, yn('Gyenge abszolút konvergencia ≠ norma abszolút általában?'), 1, 'igen'],
    [5, yn('∑ a_n z^n abszolút |z|<R, R a sugár?'), 1, 'igen'],
    [5, yn('Abel-szummáció feltételes sort is szummálhat (Grandí)?'), 1, 'igen'],
    [5, yn('Cesàro (C,1) a Grandí-sort 1/2-re szummálja?'), 1, 'igen'],
    [5, yn('Klasszikusan Grandí divergens?'), 1, 'igen'],
    [5, yn('∑ (−1)^{n+1}/n Abel-szummája ln2, és konvergens is?'), 1, 'igen'],
    [5, yn('Átrendezéssel ln2 más értékre vihető?'), 1, 'Riemann'],
    [5, yn('Pozitív tagú sor nem átrendezhető más összegre?'), 1, 'igen'],
    [5, yn('∑ |a_n| = ∞ és ∑ a_n = s ∈ ℝ ⇒ feltételes?'), 1, 'definíció'],
    [5, yn('Van divergens sor, amelynek ∑ |a_n| <∞?'), 0, 'abszolút ⇒ konv.'],
    [5, yn('Komplex Riemann-átrendezés bonyolultabb (Steinitz)?'), 1, 'igen'],
    [5, yn('Két feltételesen konvergens sor összege lehet abszolút konvergens?'), 1, 'a kiejtő tagok + abszolút maradék'],
    [5, yn('∑ (−1)^n/√n + ∑ ((−1)^{n+1}/√n + 1/n²) abszolút konvergens?'), 1, 'összeg ∑1/n²'],
    [6, yn('Banach–Steinhaus nem közvetlen abszolút teszt, de egyenletes korlátosság?'), 1, 'igen'],
    [6, yn('Pietsch: abszolút összegző operátorok elmélete?'), 1, 'igen'],
    [6, yn('ℓ¹-ben a kanonikus bázis abszolút (unconditional)?'), 1, 'igen'],
    [6, yn('c_0-ban a bázis unconditional, de a térben van nem abszolút konvergens sor?'), 1, 'igen'],
    [6, yn('Orlicz–Pettis: gyenge részsor-konvergencia ⇒ norma-konvergencia?'), 1, 'igen'],
    [6, yn('Ez összeköti a gyenge és abszolút fogalmakat?'), 1, 'részben'],
    [6, yn('Numerikus ℝ: abszolút = ∑|a_n|<∞?'), 1, 'igen'],
    [6, yn('Feltételes példák családja: (−1)^n n^{−p}, 0<p≤1?'), 1, 'p=1 feltételes, p<1 is'],
    [6, yn('p>1 ebben a családban abszolút?'), 1, 'igen'],
    [6, yn('Átrendezés nem változtatja meg az abszolút konvergens Fourier-együttható ℓ¹-összeget?'), 1, 'ha ℓ¹'],
    [6, yn('Carleson: L² Fourier pontonként, nem állítja az abszolútat?'), 1, 'igen'],
    [6, yn('Kolmogorov: van L¹ függvény divergens Fourier-sorral?'), 1, 'igen'],
    [6, yn('Abszolút konvergens Fourier (A(T)) algebra?'), 1, 'Wiener'],
    [6, yn('Wiener: 1/f is A(T)-ben, ha f≠0?'), 1, 'igen'],
    [6, yn('Numerikus gyakorlat: először abszolút teszt, aztán Leibniz/Dirichlet?'), 1, 'igen'],
    [6, yn('Ha abszolút teszt határeset, próbáld a feltételes teszteket?'), 1, 'igen'],
    [6, yn('Riemann tétel konstruktív: pozitív/negatív blokkok?'), 1, 'igen'],
    [6, yn('Az összeg tetszőleges valós szám (feltételes ℝ-sor)?'), 1, 'igen'],
    [6, yn('±∞ is elérhető átrendezéssel feltételes sornál?'), 1, 'igen'],
    [6, yn('A harmonikus alternáló sor a klasszikus feltételes példa?'), 1, 'igen'],
];

export const fvHatar: A1Row[] = [
    [1, 'lim_{x→2} (x+3) = ?', 5, '5'],
    [1, 'lim_{x→0} (5) = ?', 5, 'konstans'],
    [1, 'lim_{x→1} (x²−1)/(x−1) = ?', 2, 'x+1'],
    [1, 'lim_{x→0} (sin x)/x = ? (radián)', 1, '1'],
    [1, 'lim_{x→0} (1−cos x)/x² = ?', 0.5, '1/2'],
    [1, 'lim_{x→∞} 1/x = ?', 0, '0'],
    [1, 'lim_{x→∞} (2x+1)/(x+4) = ?', 2, '2'],
    [1, 'lim_{x→3} x² = ?', 9, '9'],
    [1, yn('lim_{x→0} 1/x létezik végesen?'), 0, 'pólus'],
    [1, 'lim_{x→0+} 1/x = +∞? (1=igen)', 1, 'igen'],
    [1, 'lim_{x→0} x sin(1/x) = ?', 0, 'rendőr'],
    [1, yn('lim_{x→0} sin(1/x) létezik?'), 0, 'oszcillál'],
    [1, 'lim_{x→0} (e^x−1)/x = ?', 1, '1'],
    [1, 'lim_{x→0} ln(1+x)/x = ?', 1, '1'],
    [1, 'lim_{x→∞} (1+1/x)^x ? Három tizedes (e).', 2.718, 'e'],
    [1, 'lim_{x→1} (x³−1)/(x−1) = ?', 3, '3'],
    [1, 'lim_{x→0} tan x / x = ?', 1, '1'],
    [1, 'lim_{x→2} (x²−4)/(x−2) = ?', 4, '4'],
    [1, yn('Ha lim f és lim g létezik, lim(f+g)=lim f+lim g?'), 1, 'igen'],
    [1, yn('lim (f g) = lim f · lim g, ha mindkettő véges?'), 1, 'igen'],
    [2, 'lim_{x→∞} (3x²+1)/(x²−x) = ?', 3, '3'],
    [2, 'lim_{x→0} (√(1+x)−1)/x = ?', 0.5, '1/2'],
    [2, 'lim_{x→∞} √(x²+x)−x = ?', 0.5, '1/2'],
    [2, 'lim_{x→0} (1−cos x)/x = ?', 0, '0'],
    [2, 'lim_{x→0+} x ln x = ?', 0, '0'],
    [2, 'lim_{x→∞} (ln x)/x = ?', 0, '0'],
    [2, 'lim_{x→∞} x / e^x = ?', 0, '0'],
    [2, 'lim_{x→0} (tan x − x)/x³ = ? Három tizedes (1/3).', 0.333, '1/3'],
    [2, yn('lim_{x→0+} e^{−1/x} = 0?'), 1, 'igen'],
    [2, yn('lim_{x→0−} e^{−1/x} = 0?'), 0, '+∞'],
    [2, 'lim_{x→1} (x^n−1)/(x−1) n=4?', 4, '4'],
    [2, 'lim_{x→0} arcsin x / x = ?', 1, '1'],
    [2, 'lim_{x→0} arctan x / x = ?', 1, '1'],
    [2, 'lim_{x→∞} arctan x = ? Három tizedes (π/2).', 1.571, 'π/2'],
    [2, yn('Bal és jobb határérték egyenlősége kell a lim létezéséhez ℝ-en?'), 1, 'igen'],
    [2, 'lim_{x→0+} |x|/x = ?', 1, '1'],
    [2, 'lim_{x→0−} |x|/x = ?', -1, '−1'],
    [2, yn('lim_{x→0} |x|/x létezik?'), 0, 'bal≠jobb'],
    [2, 'lim_{x→∞} (1+2/x)^x ? e² ≈ 7.389', 7.389, 'e²'],
    [2, 'lim_{x→0} (cos x − 1 + x²/2)/x^4 = ? −1/24 ≈ −0.042', -0.042, '−1/24'],
    [3, 'lim_{x→0} (e^x − 1 − x)/x² = ?', 0.5, '1/2'],
    [3, 'lim_{x→0} (ln(1+x)−x)/x² = ?', -0.5, '−1/2'],
    [3, 'lim_{x→∞} x sin(1/x) = ?', 1, '1'],
    [3, 'lim_{x→0+} x^x = ?', 1, 'e^{x ln x}→e^0=1'],
    [3, yn('L\'Hospital 0/0 és ∞/∞ alakban, ha a deriváltak limje létezik?'), 1, 'igen'],
    [3, yn('L\'Hospital mindig alkalmazható, ha a kimenet ∞?'), 0, 'feltételek kellenek'],
    [3, 'lim_{x→0} x² sin(1/x²) = ?', 0, 'rendőr'],
    [3, 'lim_{x→1} (ln x)/(x−1) = ?', 1, '1'],
    [3, 'lim_{x→∞} (√(x+1)−√x) = ?', 0, '0'],
    [3, 'lim_{x→0} (sinh x)/x = ?', 1, '1'],
    [3, 'lim_{x→0} (cosh x − 1)/x² = ?', 0.5, '1/2'],
    [3, 'lim_{x→π/2} (1−sin x)/(x−π/2)² ? 0.5', 0.5, '1/2'],
    [3, yn('Ha f(x)→L és L≠0, 1/f → 1/L?'), 1, 'igen'],
    [3, yn('Ha f→0 és g korlátos, f g → 0?'), 1, 'igen'],
    [3, yn('Ha f→∞ és g→∞, f−g → ∞?'), 0, 'nem feltétlen'],
    [3, 'lim_{x→0} (tan x)/sin x = ?', 1, '1'],
    [3, 'lim_{x→∞} (ln ln x)/ln x = ?', 0, '0'],
    [3, 'lim_{a→0} ( (1+a)^{1/a} ) = e ≈ 2.718', 2.718, 'e'],
    [3, yn('Összetett függvény: lim g(f(x)) = g(lim f), ha g folytonos a limnél?'), 1, 'igen'],
    [3, yn('lim_{x→a} f(x) függ f(a)-tól?'), 0, 'nem (lyukas környezet)'],
    [4, 'lim_{x→0} (sin x − x)/x³ = ? −1/6 ≈ −0.167', -0.167, '−1/6'],
    [4, 'lim_{x→0} (tan x − x)/x³ = ? 1/3 ≈ 0.333', 0.333, '1/3'],
    [4, 'lim_{x→∞} (1+1/x)^{x+1} ≈ 2.718', 2.718, 'e'],
    [4, yn('Ha lim_{x→a} f = L, akkor f korlátos a egy környezetében (lyukas)?'), 1, 'igen'],
    [4, yn('Heine: sorozatos karakterizáció a határértéknek?'), 1, 'igen'],
    [4, yn('Ha minden x_n→a, x_n≠a, f(x_n)→L, akkor lim f = L?'), 1, 'Heine'],
    [4, yn('Cauchy-kritérium függvényhatárértékre (teljes a képhalmaz)?'), 1, 'igen ℝ-ben'],
    [4, 'lim_{x→0+} x^a ln x = 0, ha a>0? (1=igen)', 1, 'igen'],
    [4, 'lim_{x→∞} x^a / e^x = 0 bármely a-ra? (1=igen)', 1, 'igen'],
    [4, 'lim_{x→∞} e^x / x^a = +∞? (1=igen)', 1, 'igen'],
    [4, yn('Aszimptota: lim (f(x)−(mx+c))=0 ⇒ ferde aszimptota?'), 1, 'igen'],
    [4, 'lim_{x→∞} (x²+1)/x − x = ?', 0, '1/x→0? (x²+1)/x − x = 1/x →0'],
    [4, 'lim_{x→0} (e^{2x}−1)/x = ?', 2, '2'],
    [4, 'lim_{x→0} (cos(3x)−1)/x² = ? −9/2 = −4.5', -4.5, '−9/2'],
    [4, yn('Kétoldali lim létezik ⇔ bal és jobb egyenlő és véges?'), 1, 'igen'],
    [4, 'lim_{x→1+} ln(x−1)? −∞ (0=nem véges). Véges? 0=nem', 0, '−∞'],
    [4, yn('lim_{x→1+} ln(x−1) véges?'), 0, '−∞'],
    [4, 'lim_{x→0} |x| = ?', 0, '0'],
    [4, yn('lim_{x→0} sgn(x) létezik?'), 0, '±1'],
    [4, 'lim_{x→∞} arctan(x²) ? π/2 ≈ 1.571', 1.571, 'π/2'],
    [5, 'lim_{x→0} (x − sin x)/x³ = ? 1/6 ≈ 0.167', 0.167, '1/6'],
    [5, 'lim_{x→0} (sinh x − x)/x³ = ? 1/6 ≈ 0.167', 0.167, '1/6'],
    [5, yn('Ha f\'(a) létezik, lim_{h→0} (f(a+h)−f(a))/h = f\'(a)?'), 1, 'definíció'],
    [5, yn('A derivált létezése implikálja a folytonosságot?'), 1, 'igen'],
    [5, yn('A folytonosság implikálja a deriváltat?'), 0, '|x| 0-ban'],
    [5, 'lim_{x→0} x² / sin x = ?', 0, '0'],
    [5, 'lim_{x→π} (sin x)/(x−π) = ?', -1, 'cos π = −1'],
    [5, yn('Végtelenben vett határérték: ∀M ∃K: x>K ⇒ f(x)>M (+∞)?'), 1, 'igen'],
    [5, yn('f=O(g) x→∞ ⇒ f/g korlátos?'), 1, 'igen'],
    [5, yn('f=o(g) ⇒ f/g → 0?'), 1, 'igen'],
    [5, yn('f ∼ g ⇔ f/g → 1?'), 1, 'igen'],
    [5, 'lim_{x→0} (1+x)^{1/x} = e ≈ 2.718', 2.718, 'e'],
    [5, 'lim_{x→∞} x (a^{1/x}−1) = ln a, a=2 ≈ 0.693', 0.693, 'ln 2'],
    [5, yn('Többváltozós lim létezése erősebb, mint az egyenes menti limek?'), 1, 'igen'],
    [5, yn('Ha két út mentén más a lim, a 2D lim nem létezik?'), 1, 'igen'],
    [5, 'lim_{(x,y)→(0,0)} (x²−y²)/(x²+y²) létezik? (1=igen)', 0, 'utak'],
    [5, 'lim_{(x,y)→(0,0)} (x y)/√(x²+y²) = ?', 0, 'rendőr'],
    [5, yn('Iterált lim_x lim_y nem mindig = lim_y lim_x?'), 1, 'igen'],
    [5, yn('Moore–Osgood: egyenletes + pontonkénti ⇒ iterált=kettős?'), 1, 'igen'],
    [5, yn('Ha a kettős határérték létezik, az iteráltak megegyeznek vele (ha léteznek)?'), 1, 'igen'],
    [6, 'lim_{x→0} (tan x − sin x)/x³ = ? 1/2', 0.5, '1/2'],
    [6, yn('Aszimptotikus sor nem feltétlen konvergens, mégis használható?'), 1, 'igen'],
    [6, yn('Stokes-jelenség: az aszimptotika a sík szektoraitól függ?'), 1, 'igen'],
    [6, 'lim_{x→0+} x^{-1} e^{−1/x} = ?', 0, '0'],
    [6, yn('Sima bump: e^{−1/x} kiterjesztése 0-ban C^∞, nem analitikus?'), 1, 'igen'],
    [6, yn('Határérték és disztribúció: δ approximációk (n ρ(n x))?'), 1, 'igen'],
    [6, yn('Főérték lim_{ε→0} ∫_{|x|>ε} dx/x = 0 szimmetrikusan?'), 1, 'igen'],
    [6, yn('Cauchy-főérték létezhet, ha a kétoldali impróprius nem?'), 1, 'igen'],
    [6, 'lim_{A→∞} ∫_1^A dx/x² = ?', 1, '1'],
    [6, yn('Impróprius ∫_1^∞ dx/x divergens, pedig 1/x→0?'), 1, 'igen'],
    [6, yn('Dominált konvergencia a lim és ∫ felcseréléséről szól?'), 1, 'igen'],
    [6, yn('Egyenletes konvergencia [a,b]-n felcseréli a limet és az integrált?'), 1, 'igen'],
    [6, yn('Pontonkénti konvergencia nem elég a lim∫=∫lim-hez?'), 1, 'igen (ellenpéldák)'],
    [6, 'lim_{A→∞} ∫_1^A e^{-x} dx = ?', 0.368, 'e^{-1} ≈ 0,368'],
    [6, 'lim n ∫_0^1 x^n dx = ?', 1, 'n/(n+1)→1'],
    [6, yn('Laplace-módszer aszimptotikát ad e^{n f} integrálokra?'), 1, 'igen'],
    [6, yn('Stacionárius fázis oszcilláló integrálokra?'), 1, 'igen'],
    [6, yn('Határérték C-ben: z→0 (e^z−1)/z = 1?'), 1, 'igen'],
    [6, yn('Komplex lim erősebb (minden irány)?'), 1, 'igen'],
    [6, yn('A valós kétoldali lim létezése gyengébb, mint a komplex lim?'), 1, 'igen'],
];

export const nevezetes: A1Row[] = [
    [1, 'lim_{x→0} (sin x)/x = ?', 1, '1'],
    [1, 'lim_{x→0} (tan x)/x = ?', 1, '1'],
    [1, 'lim_{x→0} (1−cos x)/x² = ?', 0.5, '1/2'],
    [1, 'lim_{x→0} (e^x−1)/x = ?', 1, '1'],
    [1, 'lim_{x→0} ln(1+x)/x = ?', 1, '1'],
    [1, 'lim_{n→∞} (1+1/n)^n ≈ ? Három tizedes.', 2.718, 'e'],
    [1, 'lim_{n→∞} (1−1/n)^n ≈ ? Három tizedes (1/e).', 0.368, '1/e'],
    [1, 'lim_{n→∞} n^{1/n} = ?', 1, '1'],
    [1, 'lim_{x→∞} (1+1/x)^x ≈ 2.718', 2.718, 'e'],
    [1, 'lim_{x→0} (sinh x)/x = ?', 1, '1'],
    [1, 'lim_{x→0} (arcsin x)/x = ?', 1, '1'],
    [1, 'lim_{x→0} (arctan x)/x = ?', 1, '1'],
    [1, 'lim_{x→∞} (ln x)/x = ?', 0, '0'],
    [1, 'lim_{x→∞} x / e^x = ?', 0, '0'],
    [1, 'lim_{x→0+} x ln x = ?', 0, '0'],
    [1, 'lim_{n→∞} 2^{1/n} = ?', 1, '1'],
    [1, 'lim_{n→∞} (√n) / n = ?', 0, '0'],
    [1, 'lim_{x→0} sin(3x)/x = ?', 3, '3'],
    [1, 'lim_{x→0} (1−cos(2x))/x² = ?', 2, '2'],
    [1, 'lim_{x→0} (e^{3x}−1)/x = ?', 3, '3'],
    [2, 'lim_{x→0} (1+x)^{1/x} ≈ 2.718', 2.718, 'e'],
    [2, 'lim_{n→∞} (1+2/n)^n ≈ e² ≈ 7.389', 7.389, 'e²'],
    [2, 'lim_{n→∞} (1+1/n)^{n+1} ≈ 2.718', 2.718, 'e'],
    [2, 'lim_{x→0} (tan x − x)/x³ ≈ 0.333', 0.333, '1/3'],
    [2, 'lim_{x→0} (x − sin x)/x³ ≈ 0.167', 0.167, '1/6'],
    [2, 'lim_{x→0} (sin x − x)/x³ ≈ −0.167', -0.167, '−1/6'],
    [2, 'lim_{x→0} (cosh x − 1)/x² = ?', 0.5, '1/2'],
    [2, 'lim_{n→∞} n sin(1/n) = ?', 1, '1'],
    [2, 'lim_{n→∞} n (e^{1/n}−1) = ?', 1, '1'],
    [2, 'lim_{n→∞} n ln(1+1/n) = ?', 1, '1'],
    [2, 'lim_{x→0} (1−cos x)/x = ?', 0, '0'],
    [2, 'lim_{x→∞} (√(x²+1)/x) = ?', 1, '1'],
    [2, 'lim_{n→∞} (H_n − ln n) ≈ γ ≈ 0.577', 0.577, 'Euler'],
    [2, 'lim_{n→∞} ∑_{k=1}^n 1/n · (k/n) = ? (integrál)', 0.5, '1/2'],
    [2, 'lim_{x→0} ln(1+2x)/x = ?', 2, '2'],
    [2, 'lim_{x→0} (cos x − 1 + x²/2)/x^4 ≈ −0.042', -0.042, '−1/24'],
    [2, 'lim_{n→∞} n (2^{1/n}−1) ≈ ln 2 ≈ 0.693', 0.693, 'ln 2'],
    [2, 'lim_{x→0+} x^x = ?', 1, '1'],
    [2, 'lim_{n→∞} (n!)^{1/n}/n ≈ 1/e ≈ 0.368', 0.368, 'Stirling'],
    [2, 'lim_{x→0} (e^x − 1 − x)/x² = ?', 0.5, '1/2'],
    [3, 'lim_{x→0} (ln(1+x)−x)/x² = ?', -0.5, '−1/2'],
    [3, 'lim_{n→∞} (1+1/n²)^n = ?', 1, '1'],
    [3, 'lim_{n→∞} (1+1/n²)^{n²} ≈ 2.718', 2.718, 'e'],
    [3, 'lim_{x→∞} x (a^{1/x}−1) a=e?', 1, 'ln e=1'],
    [3, 'lim_{x→0} (tan x)/sin x = ?', 1, '1'],
    [3, 'lim_{x→0} (1+x^2)^{1/x} = ?', 1, '1'],
    [3, 'lim_{n→∞} ∑_{k=0}^n 1/k! ≈ e ≈ 2.718', 2.718, 'e'],
    [3, 'lim_{n→∞} ∑_{k=1}^n 1/k² ≈ π²/6 ≈ 1.645', 1.645, 'ζ(2)'],
    [3, 'lim_{n→∞} (C(2n,n))^{1/n} / 4 = ?', 1, '1'],
    [3, 'lim_{x→0} sinh x / tan x = ?', 1, '1'],
    [3, 'lim_{x→π/2} (π/2−x) tan x = ?', 1, '1'],
    [3, 'lim_{x→0} (arcsin x − x)/x³ ≈ 0.167', 0.167, '1/6'],
    [3, 'lim_{x→0} (arctan x − x)/x³ ≈ −0.167', -0.167, '−1/6'],
    [3, 'lim_{n→∞} n² (1−cos(1/n)) = ?', 0.5, '1/2'],
    [3, 'lim_{x→∞} (ln(x+1)−ln x) = ?', 0, '0'],
    [3, 'lim_{x→0} (2^x − 1)/x = ln 2 ≈ 0.693', 0.693, 'ln 2'],
    [3, 'lim_{x→0} (log_{10}(1+x))/x = 1/ln(10) ≈ 0.434', 0.434, '1/ln 10'],
    [3, 'lim_{n→∞} (√(n+1)−√n) √n = ?', 0.5, '1/2'],
    [3, 'lim_{x→0} x / (e^x − 1) = ?', 1, '1'],
    [3, 'lim_{x→0} (cos(ax)−1)/x² = −a²/2, a=2?', -2, '−2'],
    [4, 'lim_{x→0} (e^x − e^{−x} − 2x)/x³ = ? 1/3 ≈ 0.333', 0.333, '2/6=1/3'],
    [4, 'lim_{n→∞} n ((1+1/n)^n − e) ≈ −e/2 ≈ −1.359', -1.359, '−e/2'],
    [4, 'lim_{x→0} (tan x − sin x)/x³ = ?', 0.5, '1/2'],
    [4, 'lim_{x→∞} (1 + a/x)^{bx} = e^{ab}, a=1,b=2?', 7.389, 'e²'],
    [4, 'lim_{x→0+} (ln x) / (1/x) = ?', 0, '0'],
    [4, 'lim_{n→∞} (∑_{k=1}^n k)/n² = ?', 0.5, '1/2'],
    [4, 'lim_{n→∞} (∑_{k=1}^n k²)/n³ ≈ 0.333', 0.333, '1/3'],
    [4, 'lim_{x→0} (∛(1+x)−1)/x = ?', 0.333, '1/3'],
    [4, 'lim_{x→0} ((1+x)^a − 1)/x = a, a=5?', 5, '5'],
    [4, 'lim_{n→∞} n (√[n]{e} − 1) = ?', 1, 'ln e=1'],
    [4, 'lim_{x→0} sin(sin x)/x = ?', 1, '1'],
    [4, 'lim_{x→0} (1−cos x − x²/2)/x^4 ≈ −0.042', -0.042, '−1/24'],
    [4, 'lim_{x→∞} x^n e^{−x} = 0 (n=10)? (1=igen)', 1, 'igen'],
    [4, 'lim_{x→0} (ln(1+x) − x + x²/2)/x³ ≈ 0.333', 0.333, '1/3'],
    [4, 'lim_{n→∞} (2n)! / (n!)^2 / 4^n  (centr./4^n) → 0? (1=igen)', 1, '∼ 1/√(π n)'],
    [4, 'lim_{x→1} (x^x − 1)/(x−1) = ?  (1+ln 1)=1', 1, '1'],
    [4, 'lim_{x→0} (sinh x − x)/x³ ≈ 0.167', 0.167, '1/6'],
    [4, 'lim_{x→0} (tan(2x))/x = ?', 2, '2'],
    [4, 'lim_{n→∞} (1−1/n)^{−n} ≈ e ≈ 2.718', 2.718, 'e'],
    [4, 'lim_{x→0} (e^{sin x}−1)/x = ?', 1, '1'],
    [5, 'lim_{x→0} (x cot x) = ?', 1, '1'],
    [5, 'lim_{x→0} (arcsin x)/tan x = ?', 1, '1'],
    [5, 'lim_{n→∞} n (n^{1/n} − 1) / ln n = ?', 1, '1'],
    [5, 'lim_{x→0} (1+x+x²)^{1/x} ≈ e', 2.718, 'e'],
    [5, 'lim_{x→∞} (x − x² ln(1+1/x)) = ? 0.5', 0.5, '1/2'],
    [5, 'lim_{n→∞} (H_n^{(2)}) = π²/6 ≈ 1.645', 1.645, 'ζ(2)'],
    [5, 'lim_{x→0} (sin x / x)^{1/x²} ≈ e^{−1/6} ≈ 0.846', 0.846, 'e^{−1/6}'],
    [5, 'lim_{x→0} (tan x / x)^{1/x²} ≈ e^{1/3} ≈ 1.396', 1.396, 'e^{1/3}'],
    [5, 'lim_{n→∞} (n / e)^n / n!  · √(2π n) = 1 (Stirling)? (1=igen)', 1, 'igen'],
    [5, 'lim_{x→0} (e^x + e^{−x} − 2)/x² = ?', 1, '1'],
    [5, 'lim_{x→0} (ln(1+x) / x)^{1/x} ≈ e^{−1/2} ≈ 0.607', 0.607, 'e^{−1/2}'],
    [5, 'lim_{x→∞} (√(x²+ax) − x) = a/2, a=6?', 3, '3'],
    [5, 'lim_{x→0} (∛(1+3x)−1)/x = ?', 1, '1'],
    [5, 'lim_{n→∞} ∑_{k=1}^n n/(n²+k²) ≈ π/4 ≈ 0.785', 0.785, 'arctan 1'],
    [5, 'lim_{x→0} x^{-2} (cosh x − 1 − x²/2) = 1/24 ≈ 0.042', 0.042, '1/24'],
    [5, 'lim_{x→1} (x^x − 1)/(x − 1) = ?', 1, '1'],
    [5, 'lim_{x→0} sin(x²)/x = ?', 0, '0'],
    [5, 'lim_{x→0} sin(x²)/x² = ?', 1, '1'],
    [5, 'lim_{n→∞} (1+1/n+1/n²)^n ≈ e', 2.718, 'e'],
    [5, 'lim_{x→0+} (1/x − 1/sin x) = ?', 0, '0'],
    [6, 'lim_{x→0} (tan x − x − x³/3)/x^5 = 2/15 ≈ 0.133', 0.133, '2/15'],
    [6, 'lim_{n→∞} n (e − (1+1/n)^n) ≈ e/2 ≈ 1.359', 1.359, 'e/2'],
    [6, 'lim_{x→0} (sin x · sinh x)/x² = ?', 1, '1'],
    [6, 'lim_{x→∞} (ln(1+e^x) − x) = ?', 0, '0? ln(e^x(e^{-x}+1))−x=ln(1+e^{-x})→0'],
    [6, 'lim_{x→0} (asin(x)−atan(x))/x³ ≈ 0.167', 0.167, '1/6'],
    [6, 'lim_{n→∞} (C(2n,n) √(π n) )/ 4^n = ?', 1, 'Stirling'],
    [6, 'lim_{x→0} (e^{x²} − 1 − x²)/x^4 = ?', 0.5, '1/2'],
    [6, 'lim_{x→0+} x^{sin x} = ?', 1, '1'],
    [6, 'lim_{x→∞} (x^{1/x}) = ?', 1, '1'],
    [6, 'lim_{x→0} (cos x)^{1/x²} ≈ e^{−1/2} ≈ 0.607', 0.607, 'e^{−1/2}'],
    [6, 'lim_{n→∞} ∑_{k=1}^n 1/(k(k+1)) = ?', 1, '1'],
    [6, 'lim_{x→0} (ln(1+x) − ln(1−x))/x = ?', 2, '2'],
    [6, 'lim_{x→0} ( (1+x)^{1/x} − e )/x ≈ −e/2 ≈ −1.359', -1.359, '−e/2'],
    [6, 'lim_{x→π} (sin x)/(π−x) = ?', 1, '1'],
    [6, 'lim_{x→0} (∛(1+x) − ∛(1−x))/x ≈ 0.667', 0.667, '2/3'],
    [6, 'lim_{n→∞} n ln(n/(n+1)) = ?', -1, '−1'],
    [6, 'lim_{x→0} (tan x − sin x − x³/2)/x^5 = ?', 0.125, '1/8'],
    [6, yn('A (sin x)/x → 1 a nevezetes alaplimitek egyike?'), 1, 'igen'],
    [6, yn('Az (1+1/n)^n → e nevezetes?'), 1, 'igen'],
    [6, yn('L\'Hospital a nevezetes 0/0 alakokat is igazolhatja?'), 1, 'igen'],
];

export const folytonossag: A1Row[] = [
    [1, yn('f(x)=x folytonos ℝ-en?'), 1, 'igen'],
    [1, yn('f(x)=x² folytonos ℝ-en?'), 1, 'igen'],
    [1, yn('f(x)=|x| folytonos 0-ban?'), 1, 'igen'],
    [1, yn('f(x)=|x| deriválható 0-ban?'), 0, 'nem'],
    [1, yn('f(x)=1/x folytonos 0-ban?'), 0, 'nincs értelmezve / pólus'],
    [1, yn('f(x)=1/x folytonos (0,∞)-en?'), 1, 'igen'],
    [1, yn('Polinom folytonos ℝ-en?'), 1, 'igen'],
    [1, yn('Racionális tört folytonos, ahol a nevező ≠ 0?'), 1, 'igen'],
    [1, yn('sin, cos folytonos ℝ-en?'), 1, 'igen'],
    [1, yn('exp folytonos ℝ-en?'), 1, 'igen'],
    [1, yn('ln folytonos (0,∞)-en?'), 1, 'igen'],
    [1, yn('Összeg folytonos, ha mindkét tag folytonos?'), 1, 'igen'],
    [1, yn('Szorzat folytonos, ha mindkét tényező folytonos?'), 1, 'igen'],
    [1, yn('Hányados folytonos, ha a nevező ≠ 0?'), 1, 'igen'],
    [1, yn('Összetett: g∘f folytonos, ha f és g folytonos (megfelelő helyen)?'), 1, 'igen'],
    [1, yn('sgn(x) folytonos 0-ban?'), 0, 'ugrás'],
    [1, yn('sgn(x) folytonos 1-ben?'), 1, 'igen'],
    [1, yn('Heaviside-lépcső folytonos 0-ban?'), 0, 'ugrás'],
    [1, yn('f(x)=x sin(1/x) (0-ban 0) folytonos 0-ban?'), 1, 'igen'],
    [1, yn('f(x)=sin(1/x) (0-ban 0) folytonos 0-ban?'), 0, 'oszcillál'],
    [2, yn('Folytonosság ⇔ Heine: x_n→a ⇒ f(x_n)→f(a)?'), 1, 'igen'],
    [2, yn('ε–δ: ∀ε>0 ∃δ>0: |x−a|<δ ⇒ |f(x)−f(a)|<ε?'), 1, 'definíció'],
    [2, yn('Egyenletes folytonosság: δ független a-tól egy halmazon?'), 1, 'igen'],
    [2, yn('[a,b]-n folytonos ⇒ egyenletesen folytonos?'), 1, 'Heine–Cantor'],
    [2, yn('(0,1)-en 1/x egyenletesen folytonos?'), 0, 'nem'],
    [2, yn('ℝ-en sin x egyenletesen folytonos?'), 1, 'Lipschitz'],
    [2, yn('ℝ-en x² egyenletesen folytonos?'), 0, 'nem'],
    [2, yn('Lipschitz ⇒ egyenletes folytonosság?'), 1, 'igen'],
    [2, yn('Egyenletes folytonosság ⇒ Lipschitz?'), 0, '√x [0,1]'],
    [2, yn('Megszüntethető szakadás: lim f létezik, de ≠ f(a) vagy f(a) nincs?'), 1, 'igen'],
    [2, yn('(sin x)/x 0-ban megszüntethető szakadással 1-re tehető?'), 1, 'igen'],
    [2, yn('Ugrás: bal és jobb lim létezik, de különbözik?'), 1, 'igen'],
    [2, yn('Másodfajú: legalább az egyik oldali lim nem véges / nincs?'), 1, 'igen'],
    [2, yn('1/x 0-ban másodfajú szakadás?'), 1, 'igen'],
    [2, yn('tg x π/2-ben másodfajú?'), 1, 'igen'],
    [2, 'f(x)=x, a=2. δ=ε működik Lipschitz 1 miatt? (1=igen)', 1, 'igen'],
    [2, yn('Korlátos [a,b]-n a folytonos f?'), 1, 'Weierstrass'],
    [2, yn('Nyílt (0,1)-en a folytonos f mindig korlátos?'), 0, '1/x'],
    [2, yn('Folytonos bijekció [a,b]→ℝ képe intervallum?'), 1, 'IVT + kompakt'],
    [2, yn('Inverz folytonos, ha f szigorúan monoton folytonos intervallumon?'), 1, 'igen'],
    [3, yn('Darboux: deriváltnak van Darboux-tulajdonsága (IVT), még ha nem folytonos?'), 1, 'igen'],
    [3, yn('Minden Darboux-függvény folytonos?'), 0, 'derivált ellenpélda'],
    [3, yn('Thomae-függvény folytonos irracionálisokban, szakad racionálisokban?'), 1, 'igen'],
    [3, yn('Dirichlet 1_ℚ sehol sem folytonos?'), 1, 'igen'],
    [3, yn('Riemann-függvény (1/q) folytonos irracionálisokban?'), 1, 'igen'],
    [3, yn('Hölder-α ⇒ egyenletes folytonos kompakt?'), 1, 'igen'],
    [3, yn('α>1 Hölder ℝ-en ⇒ konstans?'), 1, 'igen'],
    [3, yn('Abszolút folytonos ⇒ folytonos?'), 1, 'igen'],
    [3, yn('Folytonos ⇒ abszolút folytonos [a,b]-n?'), 0, 'Cantor-függvény'],
    [3, yn('Cantor-függvény folytonos, nem abszolút folytonos?'), 1, 'igen'],
    [3, yn('Egyenletes limesz folytonos függvényeknek folytonos?'), 1, 'igen'],
    [3, yn('Pontonkénti limesz megőrzi a folytonosságot?'), 0, 'nem'],
    [3, yn('Dini: monoton konvergencia folytonoshoz kompaktón egyenletes?'), 1, 'igen'],
    [3, yn('Weierstrass: polinomokkal egyenletesen közelíthető C[a,b]?'), 1, 'igen'],
    [3, yn('Stone–Weierstrass algebra sűrű C(K)-ban?'), 1, 'igen'],
    [3, yn('C[a,b] max-normával Banach?'), 1, 'igen'],
    [3, yn('Folytonos f kiterjeszthető a lezártra, ha egyenletesen folytonos?'), 1, 'igen'],
    [3, yn('(0,1)-en egyenletesen folytonos f kiterjed [0,1]-re?'), 1, 'igen'],
    [3, yn('1/x kiterjed folytonosan 0-ra (0,1]-ről?'), 0, 'nem'],
    [3, yn('sin(1/x) kiterjed folytonosan 0-ra?'), 0, 'nem'],
    [4, yn('Kompakt → ℝ folytonos képe kompakt?'), 1, 'igen'],
    [4, yn('Összefüggő → ℝ folytonos képe összefüggő?'), 1, 'igen'],
    [4, yn('Nyílt halmaz folytonos képe nyílt?'), 0, 'nem (konstans)'],
    [4, yn('Zárt halmaz folytonos képe zárt?'), 0, 'nem'],
    [4, yn('Homeomorfizmus nyíltat nyíltba visz?'), 1, 'igen'],
    [4, yn('f(x)=x² : ℝ→[0,∞) homeomorfizmus?'), 0, 'nem injektív'],
    [4, yn('exp: ℝ→(0,∞) homeomorfizmus?'), 1, 'igen'],
    [4, yn('arctan: ℝ→(−π/2,π/2) homeomorfizmus?'), 1, 'igen'],
    [4, yn('Lokális Lipschitz ⇒ folytonos?'), 1, 'igen'],
    [4, yn('C¹ ⇒ lokálisan Lipschitz?'), 1, 'igen'],
    [4, yn('C^0 \\ C¹ nemüres (|x|)?'), 1, 'igen'],
    [4, yn('Analitikus ⇒ C^∞?'), 1, 'igen'],
    [4, yn('C^∞ ⇒ analitikus?'), 0, 'e^{−1/x²}'],
    [4, yn('Bump-függvény C^∞, kompakt tartójú, nem azonosan 0?'), 1, 'igen'],
    [4, yn('Folytonos periodikus f egyenletesen folytonos ℝ-en?'), 1, 'igen'],
    [4, yn('Korlátos + egyenletesen folytonos ⇒ kiterjeszthető kompaktifikációra?'), 1, 'gyakran'],
    [4, yn('Osc(f,a)=0 ⇔ folytonos a-ban?'), 1, 'igen'],
    [4, yn('Szakadási halmaz monoton függvénynél megszámlálható?'), 1, 'igen'],
    [4, yn('Monoton függvény szabályozott (regulated)?'), 1, 'igen'],
    [4, yn('Szabályozott függvény Riemann-integrálható?'), 1, 'igen (korlátos, megszámlálható ugrás)'],
    [5, yn('Luzin: mérhető f majdnem folytonos (ε-kompakt)?'), 1, 'igen'],
    [5, yn('Vitali–Carathéodory: mérhető approximálható folytonossal?'), 1, 'igen'],
    [5, yn('Tietze: zárt Z-n folytonos kiterjed a térre (normált)?'), 1, 'igen'],
    [5, yn('Urysohn: diszjunkt zártak elválasztása folytonos függvénnyel?'), 1, 'igen'],
    [5, yn('Baire 1. osztály: pontonkénti limesz folytonosaknak, Darboux?'), 1, 'Baire-1 Darboux'],
    [5, yn('Baire 1 szakadási halmaza 1. kategória?'), 1, 'igen'],
    [5, yn('Egyenletes konvergencia C(K)-ban a norma-konvergencia?'), 1, 'igen'],
    [5, yn('Ascoli: egyenletes korlát + egyenlőn folytonos ⇒ rel. kompakt C(K)?'), 1, 'igen'],
    [5, yn('Hölder-gömb C[a,b]-ben relatív kompakt?'), 1, 'igen (Ascoli)'],
    [5, yn('Folytonos modulus ω(δ)→0 ⇔ egyenletes folytonosság?'), 1, 'igen'],
    [5, yn('Kontrakció egyenletesen folytonos?'), 1, 'igen'],
    [5, yn('Isometria folytonos?'), 1, 'igen'],
    [5, yn('Nyílt leképezés tétel: Banach-tér folytonos szürjekció nyílt?'), 1, 'igen'],
    [5, yn('Zárt gráf: zárt gráf + Banach ⇒ folytonos lineáris?'), 1, 'igen'],
    [5, yn('Korlátos lineáris = folytonos lineáris (normált)?'), 1, 'igen'],
    [5, yn('Minden lineáris ℝ^n→ℝ^m folytonos?'), 1, 'igen'],
    [5, yn('Végtelen dimenzióban van nemfolytonos lineáris (AC-vel)?'), 1, 'igen'],
    [5, yn('Koordináta-függvények ℝ^n-en folytonosak?'), 1, 'igen'],
    [5, yn('Max-norma és euklideszi norma ekvivalens ℝ^n-en ⇒ ugyanaz a folytonosság?'), 1, 'igen'],
    [5, yn('Folytonosság topologikus fogalom, nem függ a metrika számitól ekvivalencia erejéig?'), 1, 'igen'],
    [6, yn('Whitney-kiterjesztés C^k jetekre?'), 1, 'igen'],
    [6, yn('Seeley kiterjesztés féltérről C^∞?'), 1, 'igen'],
    [6, yn('Partíció az egység C^∞ parakompakt sokaságon?'), 1, 'igen'],
    [6, yn('Folytonos függvény algebrája C(K) Banach-algebra?'), 1, 'igen'],
    [6, yn('Gelfand–Naimark C(K)-t kommutatív C*-algebraként karakterizál?'), 1, 'igen'],
    [6, yn('Sard: kritikus értékek 0 mértékűek C^∞-nál?'), 1, 'igen'],
    [6, yn('Morse–Sard feltételei a simaságra?'), 1, 'igen'],
    [6, yn('Folytonos injekció ℝ→ℝ szigorúan monoton?'), 1, 'igen'],
    [6, yn('Folytonos injekció [0,1]→ℝ² lehet térkitöltő? (nem injektív Peano)'), 0, 'Peano nem injektív; injektív folytonos [0,1]→ℝ² nem kitöltő (invariáns)'],
    [6, yn('Injektív folytonos [0,1]→ℝ^n képe homeomorf [0,1]-gyel?'), 1, 'igen'],
    [6, yn('Jordan: egyszerű zárt görbe ℝ²-t két komponensre oszt?'), 1, 'igen'],
    [6, yn('Schoenflies a Jordan-görbére?'), 1, 'igen 2D'],
    [6, yn('Folytonos kiterjesztés Cauchy-sorozattal teljes térbe?'), 1, 'egyenletes folytonosság'],
    [6, yn('Hölder-kitevő infimuma a modulusból olvasható?'), 1, 'igen'],
    [6, yn('Zygmund-osztály a Lipschitz és C¹ között?'), 1, 'igen'],
    [6, yn('Folytonos függvény Riemann-integrálható [a,b]-n?'), 1, 'igen'],
    [6, yn('Korlátos, megszámlálható szakadású Riemann-integrálható?'), 1, 'igen'],
    [6, yn('Volterra: van derivált, ami nem Riemann-integrálható?'), 1, 'igen'],
    [6, yn('Korlátos derivált Riemann-integrálható?'), 1, 'igen (Darboux + korlátos)'],
    [6, yn('Alaptétel: F(x)=∫_a^x f, f folytonos ⇒ F\'=f?'), 1, 'igen'],
];

export const folytonosTetelek: A1Row[] = [
    [1, yn('Bolzano (IVT): folytonos [a,b]-n, f(a)<0<f(b) ⇒ van gyök?'), 1, 'igen'],
    [1, yn('IVT: a kép intervallum?'), 1, 'igen'],
    [1, yn('Weierstrass: folytonos [a,b]-n felveszi min/max-ot?'), 1, 'igen'],
    [1, yn('Weierstrass nyílt (0,1)-en is mindig min-t ad?'), 0, 'nem, 1/x'],
    [1, yn('Heine–Cantor: kompaktón folytonos ⇒ egyenletesen folytonos?'), 1, 'igen'],
    [1, yn('Kompakt képe kompakt folytonos f mellett?'), 1, 'igen'],
    [1, yn('Összefüggő képe összefüggő?'), 1, 'igen'],
    [1, 'f(x)=x³−x−1 [1,2]-en. f(1)=−1<0<f(2)=5. Van gyök? (1=igen)', 1, 'IVT'],
    [1, 'f(x)=e^x + x, f(0)=1>0, f(−1)=1/e−1<0. Van gyök? (1=igen)', 1, 'IVT'],
    [1, yn('sin x = x/2-nek van megoldása (0,π)-ben?'), 1, 'IVT grafikonon'],
    [1, yn('Konstans Weierstrass szerint min=max?'), 1, 'igen'],
    [1, yn('f(x)=x (0,1)-en felvette a 0-t?'), 0, '0 nincs a képen'],
    [1, yn('f(x)=x [0,1]-en felveszi a 0-t és 1-et?'), 1, 'igen'],
    [1, yn('Darboux (IVT deriváltra) gyöket ad f\'-nek?'), 1, 'igen'],
    [1, yn('Rolle: f(a)=f(b) folytonos, deriválható (a,b)-n ⇒ f\'(c)=0?'), 1, 'igen'],
    [1, yn('Lagrange MVT: van c, f\'(c)=(f(b)−f(a))/(b−a)?'), 1, 'igen'],
    [1, yn('Cauchy MVT: f\'/g\' alakú középérték?'), 1, 'igen'],
    [1, yn('MVT ⇒ Rolle speciális eset?'), 0, 'fordítva: Rolle-ból MVT'],
    [1, yn('Fixpont: f:[a,b]→[a,b] folytonos ⇒ van x=f(x)?'), 1, 'Brouwer 1D / IVT'],
    [1, yn('cos x = x-nek van megoldása ℝ-en?'), 1, 'igen, Dottie'],
    [2, yn('Ha f\'>0 (a,b)-n, f szigorúan nő?'), 1, 'MVT'],
    [2, yn('Ha f nő, akkor f\'≥0 ahol létezik?'), 1, 'igen'],
    [2, yn('f\'≥0 ⇒ f monoton növő (intervallumon, ha f deriválható)?'), 1, 'MVT'],
    [2, 'f(x)=x² [−1,1], min? ', 0, '0'],
    [2, 'f(x)=x² [−1,1], max?', 1, '1'],
    [2, 'f(x)=sin x [0,π], max?', 1, '1'],
    [2, 'f(x)=sin x [0,π], min?', 0, '0'],
    [2, yn('Szélsőérték belső ponton f\'=0 vagy nem deriválható?'), 1, 'Fermat'],
    [2, yn('Globális min kompaktón létezik folytonosnál?'), 1, 'Weierstrass'],
    [2, yn('Lokális min ⇒ globális?'), 0, 'nem'],
    [2, yn('IVT háromszor alkalmazható, ha 3 előjelváltás van?'), 1, 'igen'],
    [2, yn('Páratlan fokú valós polinomnak van valós gyöke?'), 1, 'IVT + ∞ viselkedés'],
    [2, yn('Páros fokú pozitív főegyütthatójúnak mindig van valós gyöke?'), 0, 'x²+1'],
    [2, yn('e^x = 2x+3-nak van megoldása?'), 1, 'IVT'],
    [2, yn('Egyenletes folytonosság megőrzi Cauchy-sorozatot?'), 1, 'igen'],
    [2, yn('Kompaktón a folytonos bijekció homeomorfizmus a képére?'), 1, 'igen'],
    [2, yn('Nyílt intervallumon a folytonos bijekció inverze folytonos?'), 1, 'igen'],
    [2, yn('Brouwer nD: gömb önmagába folytonos ⇒ fixpont?'), 1, 'igen'],
    [2, yn('Schauder: kompakt konvex Banach-halmaz folytonos önleképezése fixpontos?'), 1, 'igen'],
    [2, yn('Banach-fixpont: kontrakció teljes téren egyértelmű fixpont?'), 1, 'igen'],
    [3, yn('Taylor MVT-maradékkal (Lagrange-maradék)?'), 1, 'igen'],
    [3, yn('Cauchy-maradék a Taylorhoz?'), 1, 'igen'],
    [3, yn('Integrálmaradék a Taylorhoz?'), 1, 'igen'],
    [3, yn('L\'Hospital MVT/Cauchy MVT következménye?'), 1, 'igen'],
    [3, yn('Darboux-tulajdonság: közbülső értékek, nem feltétlen folytonos?'), 1, 'igen'],
    [3, yn('f\' Darboux, tehát f\'-nek nincs ugrása?'), 1, 'igen'],
    [3, yn('sgn-szerű ugrás nem lehet derivált?'), 1, 'igen'],
    [3, yn('Volterra-példa: van derivált, ami nem Riemann-integrálható?'), 1, 'igen'],
    [3, yn('Alaptétel: folytonos f-re F\'=f?'), 1, 'igen'],
    [3, yn('Ha F\'=0 intervallumon, F konstans?'), 1, 'MVT'],
    [3, yn('Ha F\'=G\', F−G konstans?'), 1, 'igen'],
    [3, yn('Integrálközép: van c, f(c)= (1/(b−a))∫f, f folytonos?'), 1, 'IVT + alaptétel'],
    [3, yn('Súlyozott középérték integrálra (f≥0, g folytonos)?'), 1, 'igen'],
    [3, yn('Van-e c, hogy ∫_a^b f = f(c)(b−a), ha f folytonos?'), 1, 'integrálközép'],
    [3, yn('Weierstrass approximáció C[a,b]-n?'), 1, 'igen'],
    [3, yn('Stone általánosítja algebrákra?'), 1, 'igen'],
    [3, yn('Peano létezés ODE-re folytonos jobb oldallal (lokális)?'), 1, 'igen'],
    [3, yn('Picard–Lindelöf Lipschitz ⇒ egyértelműség?'), 1, 'igen'],
    [3, yn('Peano nem ad egyértelműséget?'), 1, 'igen'],
    [3, yn('Gronwall egyenlőtlenség a folytonos/integrál becslésekről?'), 1, 'igen'],
    [4, yn('Arzelà–Ascoli kompaktság C[a,b]-ben?'), 1, 'igen'],
    [4, yn('Stolz–Cesàro diszkrét L\'Hospital?'), 1, 'hasonló'],
    [4, yn('Dini tétel monoton konvergenciára kompaktón?'), 1, 'igen'],
    [4, yn('Egorov: m.m. konvergencia majdnem egyenletes véges mértéken?'), 1, 'igen'],
    [4, yn('Luzin: mérhető majdnem folytonos?'), 1, 'igen'],
    [4, yn('Scorza-Dragoni: Carathéodory f majdnem folytonos (t,x)-ben?'), 1, 'igen'],
    [4, yn('Michael-szelekció: l.s.c. konvex zárt értékű (parakompakt)?'), 1, 'igen'],
    [4, yn('Tietze kiterjesztés?'), 1, 'igen'],
    [4, yn('Hahn–Banach analitikus forma folytonos lineáris kiterjesztés?'), 1, 'igen'],
    [4, yn('Banach–Alaoglu: zárt gömb gyenge*-kompakt?'), 1, 'igen'],
    [4, yn('Weierstrass Extreme Value általánosítása: kompakt Hausdorff → ℝ?'), 1, 'igen'],
    [4, yn('IVT általánosítása: összefüggő kép összefüggő?'), 1, 'igen'],
    [4, yn('Középértéktétel ℝ^n-ben: van c, Df(c)(b−a)=f(b)−f(a)?'), 1, 'igen (komponensenként / Lagrange)'],
    [4, yn('Többváltozós Rolle gömbre / konvexre?'), 1, 'van változat'],
    [4, yn('Inverzfüggvény-tétel: C¹, Df invertálható ⇒ lokális C¹ inverz?'), 1, 'igen'],
    [4, yn('Implicitfüggvény-tétel C¹-re?'), 1, 'igen'],
    [4, yn('Lokális Lipschitz + Picard iteráció = Banach-fixpont?'), 1, 'igen'],
    [4, yn('Kompakt operátor Schauder-fixpontja Banachban?'), 1, 'igen'],
    [4, yn('Brouwer nem igaz végtelen dimenzióban a zárt gömbre?'), 1, 'igen, ellenpélda'],
    [4, yn('Riesz: zárt gömb kompakt ⇔ véges dimenzió?'), 1, 'igen'],
    [5, yn('Sard: kritikus értékek 0 mértékűek?'), 1, 'igen'],
    [5, yn('Morse: nem degenerált kritikus pontok izoláltak?'), 1, 'igen'],
    [5, yn('Morse-lemma kvadratikus alakra hoz?'), 1, 'igen'],
    [5, yn('Brouwer-fok folytonos leképezések topológiai invariánsa?'), 1, 'igen'],
    [5, yn('Borsuk–Ulam: S^n→ℝ^n antipodális egybeesés?'), 1, 'igen'],
    [5, yn('Ham-sandwich folytonos „szeletelés”?'), 1, 'igen'],
    [5, yn('Perron–Frobenius: pozitív mátrix pozitív sajátvektor (folytonos kúp)?'), 1, 'igen'],
    [5, yn('Krein–Rutman pozitív operátorra?'), 1, 'igen'],
    [5, yn('Crandall–Rabinowitz elágazás folytonos/C¹ családokra?'), 1, 'igen'],
    [5, yn('Leray–Schauder-fok kompakt perturbációkra?'), 1, 'igen'],
    [5, yn('Schauder-becslés elliptikus PDE-re (C^{2,α})?'), 1, 'igen'],
    [5, yn('Maximum-elv elliptikusra: max a peremen (folytonos megoldás)?'), 1, 'igen'],
    [5, yn('Hopf-lemma a peremen?'), 1, 'igen'],
    [5, yn('Variációs Weierstrass: koercív alsó félfolytonos ⇒ min?'), 1, 'igen'],
    [5, yn('Direkt módszer: gyenge alsó félfolytonosság + koercivitás?'), 1, 'igen'],
    [5, yn('Ekeland variációs elv teljes metrikus téren?'), 1, 'igen'],
    [5, yn('Mountain-pass (Ambrosetti–Rabinowitz) C¹ funkcionálra?'), 1, 'igen'],
    [5, yn('Palais–Smale feltétel a min-max palacknyakhoz?'), 1, 'igen'],
    [5, yn('Deformációlemma folytonos/C¹ pseudo-gradienssel?'), 1, 'igen'],
    [5, yn('Lusternik–Schnirelmann kategória több kritikus pontra?'), 1, 'igen'],
    [6, yn('Nash–Moser implicitfüggvény sima Fréchet-tereken?'), 1, 'igen'],
    [6, yn('Lyapunov–Schmidt redukció elágazáshoz?'), 1, 'igen'],
    [6, yn('Center manifold C^k vektormezőre?'), 1, 'igen'],
    [6, yn('Hartman–Grobman: hiperbolikus pont C^0 linearizálás?'), 1, 'igen'],
    [6, yn('Hartman–Grobman nem C¹ általában?'), 1, 'igen, csak C^0'],
    [6, yn('Peano-felület / uniqueness failure folytonos ODE-re?'), 1, 'igen'],
    [6, yn('Osgood-feltétel egyértelműséghez gyengébb Lipschitznél?'), 1, 'igen'],
    [6, yn('Nagumo, Kamke egyértelműségi feltételek?'), 1, 'igen'],
    [6, yn('Gronwall élesíthető folytonos u(t)-re integrálegyenlőtlenséggel?'), 1, 'igen'],
    [6, yn('Ascoli + Peano: Euler-töröttvonalak kompaktak?'), 1, 'igen'],
    [6, yn('Cauchy–Kovalevskaya analitikus PDE lokális létezés?'), 1, 'igen'],
    [6, yn('Holmgren egyértelműség analitikus együtthatókra?'), 1, 'igen'],
    [6, yn('Sobolev-beágyás W^{1,p}⊂C^0 alkalmas p>n?'), 1, 'igen'],
    [6, yn('Morrey: Hölder-regularitás Sobolevból?'), 1, 'igen'],
    [6, yn('Rellich–Kondrachov kompakt beágyás?'), 1, 'igen'],
    [6, yn('Poincaré-egyenlőtlenség W_0^{1,p}-n?'), 1, 'igen'],
    [6, yn('Riesz-reprezentáció Hilbertben folytonos lineárisakra?'), 1, 'igen'],
    [6, yn('Lax–Milgram folytonos koercív bilinearformára?'), 1, 'igen'],
    [6, yn('Fredholm-alternatíva kompakt perturbációra?'), 1, 'igen'],
    [6, yn('Spektrálelmélet: kompakt önadjungált sajátvektor-bázis?'), 1, 'igen'],
];

